### PR TITLE
LPS-127963 format current date value if not initialValueMemoized

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPS-127963

When changing to a locale with a format in which the current date is incorrect (20/02/2020 to MM/dd/yyyy) it put a invalid value and shows a message of error on the datePicker (and you can't change it again without exiting the WC)

So format the current value seems to solve it, not only the initialValueMemoized

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
comes from https://github.com/liferay-lima/liferay-portal/pull/1537#issuecomment-784390612

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
Hi @AliciaGarciaGarcia,

I'm closing this pull because this issue is no longer reproducible on master (please, see my [comment](https://issues.liferay.com/browse/LPS-127963?focusedCommentId=2380776&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2380776) on Jira). Apart from that, it looks like the failing test is related to your changes in this pull.

Thanks

**Pull request closed without merging**
