### PR TITLE
LPS-128696 update gradle dependencies

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-128696

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
Please add the "Review Pending" label again when the required changes were made.

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Fast like a bullet, @marcosapmf 😂

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @marcosapmf @rodrigopaulino,

I want to make some changes on JournalConverterImpl, to avoid this 

```
if (StringUtil.equals(
         ddmFormField.getType(), DDMFormFieldTypeConstants.CHECKBOX_MULTIPLE) &&
(options.size() == 1)) {
`
The idea is moved this logic to JournalTransformer, and keep everything as clean as possible. So, Can I pick this pr and make those changes on top of it?

Regards,
Eudaldo

**Comment by marcosapmf** [comment]
It's fine to me too @ealonso :)

Thank you very much

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4065

cc: @marcosapmf @rodrigopaulino

**Pull request closed without merging**
