### PR TITLE
LPS-127365 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Review by jeyvison — APPROVED** [review]
LGTM

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — APPROVED** [review]
LGTM !

**Comment by marcelabc** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:reevaluate:1012004_6412

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
resend: https://github.com/liferay-data-engine/liferay-portal/pull/196

**Pull request closed without merging**
