### PR TITLE
LPS-130971 Adding spaces to predefinedValue field of Documents and Media field causes Javascript exception

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi !
Could you please review this pull request?
The definition of the structure can contains values ​​that contain unnecessary spaces after saving that can later mess up the operation of the portal. I want to prevent this with that fix.
More info [here](https://issues.liferay.com/browse/LPP-40924?focusedCommentId=2423403&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2423403)

Thank you and best regards,
Marci

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
Hi @liferay-data-engine team, 
I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.
Thank you and best regards,
Marci

**Comment by rodrigopaulino** [comment]
Sure thing, @MarcellGyopos.

Your pull request is definitely in our pipeline. Unfortunately, we're facing heavy load from other fronts, so reviews are delayed.

Thanks for understanding.

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
