### PR TITLE
LPS-123181 prevent overriding name attribute with a broken value

### PR DESCRIPTION
**Pull request by marcosapmf**
Related Issue: https://issues.liferay.com/browse/LPS-123181

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
ci:forward

**Pull request closed without merging**
