### PR TITLE
LPS-128617 on the fieldSets the field localizable is null because is not part of the settings, and the localizable field is true by default, so in the case of the null case is applying the default value

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Hi,

Another solution is to add the _localizable_ on _FieldSetDDMFormFieldTypeSettings_ but the _localizable_ attribute will appear **always** on the screen. But this way we are assuring that the default value is true as on https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-api/src/main/java/com/liferay/dynamic/data/mapping/form/field/type/DefaultDDMFormFieldTypeSettings.java#L97

Thanks @marcelabc for the help!!

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hi @AliciaGarciaGarcia  :) I dont think these ones are flaky. Can you please check them? Thanks =D

**Comment by AliciaGarciaGarcia** [comment]
Hi @jeyvison and @marcelabc  (@liferay-data-engine )

Please, can you check https://github.com/liferay-data-engine/liferay-portal/pull/309 and https://github.com/liferay-data-engine/liferay-portal/pull/310 and decide what is the better aproach to solve the issue.

Please choose the draft you prefer (if any suits you) and I will create the PR.

Thanks!

**Pull request closed without merging**
