### PR TITLE
LPS-132016 Use custom error message in case it exists

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-132016

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
The relevant suite can only be run when https://github.com/liferay-data-engine/liferay-portal/pull/450 gets merged. Therefore, it's blocked.

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
