### PR TITLE
LPS-122340 Remove UpgradeDDMFormInstanceReportTest since we cannot copy over the data from DDMContent now that we save the data in the DDMField service.

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:forms

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Waiting for Renato's review

**Comment by natocesarrego** [comment]
@jeyvison, regarding Forms test suite, there are no related failures. 🟢 light to me. 🙂

**Comment by ealonso** [comment]
ci:test:echo

**Comment by manoelcyreno** [comment]
ci:test:lima

**Comment by jeyvison** [comment]
Hello @liferay-echo and @liferay-lima teams. Were you able to analyze the test results?

**Comment by Tim-Cao** [comment]
Hi @jeyvison, the failure cases from ci:test:echo are not related to your changes.

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
sent to https://github.com/shuyangzhou/liferay-portal/pull/9635

**Pull request closed without merging**
