### PR TITLE
LPS-132788 Create a feature flag to the new field

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
LGTM 🎉

**Comment by marcelabc** [comment]
Hi @rodrigopaulino ,
I made your suggestions and I fixed the unit test because of the new condition in the rule (the second one related to the layout field)
Thanks!

**Review by rodrigopaulino — APPROVED** [review]

**Comment by rodrigopaulino** [comment]
Please wait to run the relevant again tomorrow in order to give time for the kernel's version to be updated/synced.

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-data-engine/liferay-portal/pull/491

**Pull request closed without merging**
