### PR TITLE
LRQA-66228 Making sure the list has 2 structures

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:help

**Comment by guilhermedcamacho** [comment]
ci:test:backend

**Comment by guilhermedcamacho** [comment]
ci:test:backend

**Comment by mateussgn** [comment]
@guilhermedcamacho I've closed this PR due to the conflicted files and resent here: https://github.com/mateussgn/liferay-portal/pull/22.

**Pull request closed without merging**
