### PR TITLE
LPS-132437 Migrate dynamic data template selection modals

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Resending #472

### CODE REVIEW

**Comment by choliveira84** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Hey @markocikos ,

I took a look in your code and everything looks fine. I just have one question that raised while I was testing, it's about the title of tab in modal, in Master it shows "Forms", and in your branch it shows "Field Sets", did you do it intentionally?

**Before**
LPS-132437 before

**After**
LPS-132437 after

**Comment by markocikos** [comment]
Followup in https://github.com/liferay-data-engine/liferay-portal/pull/483

**Comment by markocikos** [comment]
ci:close

**Pull request closed without merging**
