### PR TITLE
[DE-Migration] LPS-125879 Mock setDataRecord implementation in frontend test because the creation of the dataRecordValues object is not in this module anymore

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-125879

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@interaminense, I've fixed that issue reported by you over Slack. Could you please review if it's ok, now?

**Comment by interaminense** [comment]
> @interaminense, I've fixed that issue reported by you over Slack. Could you please review if it's ok, now?
> The diff is only in this commit: [5011fc4](https://github.com/liferay-data-engine/liferay-portal/commit/5011fc4c15462a3c3a8149d02f5303244637d60d)
> 
> Basically, I've noticed that, on current master, in case the value is undefined, an empty array is passed. So I've made sure this verification is here too.

Thank you for the fix, @rodrigopaulino!

**Comment by interaminense** [comment]
LGTM!

**Comment by ealonso** [comment]
ci:reevaluate:1212004_7550

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
sent to Brian: see https://github.com/brianchandotcom/liferay-portal/pull/98566

**Pull request closed without merging**
