### PR TITLE
LPS-127725 Use syncvalue hook so that new prop values will update the component state

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Taking a look at the test failures

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hi @victorg1991,
Unfortunately, I tried to replicate the bug with your changes and could not reproduce the expected result 😞  I don't know if a code, that got merged, did something with your solution...
Please, see the video:

https://user-images.githubusercontent.com/15161924/107821992-27f94b00-6d5c-11eb-83ca-c0e96585f0f5.mp4

**Comment by victorg1991** [comment]
Hey @marcelabc thanks for the heads up, It should be fixed now :)

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Btw I've pulled the brian repo, as the main repo is not being synchronize. This way I've taken into account all possible changes that are in brian master

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Resend https://github.com/liferay-data-engine/liferay-portal/pull/224

@victorg1991 I found 1 scenario that wasn't working, I fixed and I am resending 👍 Thank you!!

**Comment by victorg1991** [comment]
Thanks!!

**Pull request closed without merging**
