### PR TITLE
LPS-123848 Documents not visible when editing dynamic data lists, after upgrade from 6.2 to DXP

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

This new upgrade process adds the "title" to the field with the "ddm-documentlibrary" type so the file name will be visible in the edit mask.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hi @IstvanD , how you doing? ^^
Thanks for your fix man. I see you're changing some data in DDMContent. We are in the middle of not using DDMContent anymore so i can't have it forward for now. 
This is the PR that will change how we are storing the data: https://github.com/liferay-data-engine/liferay-portal/pull/38

you will probably need to do your fix on top of it after it's merged in master. I'm gonna close it for now and you can talk with me if you have any doubts. 

I'm planning to have it forwarded to Shuyang today(i hope).

**Comment by IstvanD** [comment]
Hi @jeyvison 

I'm doing great, I'm hoping the same for you. :)
The changes I submitted are the fix for a customer reported issue on 7.2. My plan was to backport it to 7.2 after the fix is committed to master.

Will DDMContent pulled from 7.2 as well? If not, I could maybe send these changes directly to 7.2.x?

Please let me know your thoughts.

Thank you and best regards,
István

**Comment by jeyvison** [comment]
It won't. you can send it directly to 7.2 :)

**Comment by IstvanD** [comment]
OK, I'll do so, thanks!

**Comment by IstvanD** [comment]
Sent: https://github.com/liferay/liferay-portal-ee/pull/21842

**Pull request closed without merging**
