### PR TITLE
LPS-132437 Migrate dynamic data template selection modals

### PR DESCRIPTION
**Pull request by rodrigopaulino**
I went ahead and created a new one.

cc @markocikos.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@markocikos, I wasn't unsure if you were still in your working hours, so I decided to start testing to speed things a little bit. Let me know if you have additional work to be done to this so I can close it and you can send us a new one.

Thanks for understanding.

**Comment by markocikos** [comment]
@rodrigopaulino Thank you for pushing this! I don't have additional work to do on this PR, unless you or CI find something to improve or fix.

**Comment by rodrigopaulino** [comment]
Great. I'll wait for CI's result to start reviewing this. 

Thanks for responding so quickly.

**Comment by guilhermedcamacho** [comment]
Hey @markocikos ,

Could you fix semantic versioning occurred in relevant test and resend your PR?

I'm closing this PR from Rodrigo's repository. As you start work earlier than us, it will be faster to submit by yourself and start the relevant tests again.

Thanks and sorry for the inconvenience.

**Pull request closed without merging**
