### PR TITLE
LPS-136287 If the field is numeric and non localizable we should retr…

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you review this pull request, please?

Thanks.

Regards.

/cc @rodrigopaulino

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Review by rodrigopaulino — COMMENTED** [review]
Hey, @antonio-ortega. Thanks for sending this for review.

I understand your original fix was aimed for Web Content in previous versions, but did you check this in DDL? I'm not entirely sure your fix is reproducing the expected results from the ticket. Please check the video below:

https://user-images.githubusercontent.com/11450348/127507762-6cbcb568-b7e7-41c8-8155-3dff5cba5216.mp4

**Comment by antonio-ortega** [comment]
Hi Rodrigo,

Yes, I did. And because of that I updated LPS description accordingly. Maybe it's not clear enough the step:

> _In the Data Definition create a new structure include a numeric field._

Because I meant a field of type "Number" and in your video you selected a field of type "Decimal".

I guess we just need to extend the condition to fields of type "Number" or "Decimal". What do you think?

Thanks.

Regards.

**Comment by rodrigopaulino** [comment]
Oh, I see it now. Thanks for clarifying, @antonio-ortega.

Indeed, your solution fixes the problem for Number fields and it looks good to me.

Also, extending the behavior to Decimal fields sounds good. Do you feel this can be copied to that type of field seamlessly?
If you don't mind doing it, it would be great to keep both types consistent with each other. 
If you find that extending the behavior is a bit cumbersome, you can just comment `ci:forward` here to deliver this solution and report the bug for Decimal fields.

I'll wait for your decision. 😀 

Thanks for contributing.

**Comment by antonio-ortega** [comment]
Hi @rodrigopaulino ,

I've just pushed the same change for decimal fields.

Thanks.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Review by rodrigopaulino — APPROVED** [review]
LGTM!

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
