### PR TITLE
LPS-133831 The Number and Boolean fields value changes after upgrade

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
resend from : https://github.com/liferay-lima/liferay-portal/pull/1963

We must check if the fileEntryType is associated with some other via an DDMStructureLink and in that case format a convert those too.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
After seeing the result of test relevant of https://github.com/liferay-lima/liferay-portal/pull/1963, the errors on https://github.com/liferay-data-engine/liferay-portal/pull/553#issuecomment-865746642 should not be related

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1077401_7254

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1077401_7254

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
