### PR TITLE
LPS-127963 localized value coming from datepicker is a date so we need to convert it into a string

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-127963

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
LGTM

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
@marcelabc, I'm sending this one with some changes. Sorry for not closing it sooner.

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-data-engine/liferay-portal/pull/293

**Pull request closed without merging**
