### PR TITLE
LPS-128562 Sort fieldsDisplay on the correct hierarchy

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-128562

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @mateussgn,

Could you please verify if this issue https://issues.liferay.com/browse/LPS-128214 is not happening again? The code that you are moving was added to fix this issue.

Regards,
Eudaldo

**Comment by mateussgn** [comment]
Sure @ealonso! Thanks for letting me know. Doing it right now.

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
resent https://github.com/liferay-data-engine/liferay-portal/pull/300

**Pull request closed without merging**
