### PR TITLE
LPS-125203 SF

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
@ealonso  I did a minor SF but thinking twice the way you separated the  setNamespacedAttribute makes me think that order matters in this case. Does it matter at all or is where i put it?

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
