### PR TITLE
LPS-132789 Create the contributor class of the Address field

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related ticket: https://issues.liferay.com/browse/LPS-132789
Resending #521

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
