### PR TITLE
LPS-121875 Migrate management toolbar v2 usages in dynamic-data-mapping modules

### PR DESCRIPTION
**Pull request by markocikos**
Ticket: https://issues.liferay.com/browse/LPS-121875

In this PR we are migrating management toolbars in DDM modules to new tags based on Clay v3.

Initially I opened https://github.com/liferay-frontend/liferay-portal/pull/826, that branched into https://github.com/liferay-frontend/liferay-portal/pull/833 and this PR. We are using the newly minted `searchInputAutoFocus` in this PR.

Test plan is to ensure management toolbars maintain all features. The updated ones are on these pages:
1. C&D > Dynamic Data Lists > Ellipsis icon > Manage Data Definitions
1. C&D > Dynamic Data Lists > Create New List > Data Definition > Select
1. Design > Widget Templates
1. C&D > Forms > Forms and Element Sets tabs
1. C&D > Forms > Data Providers tab
1. Publish a form and submit it. C&D > Forms > Ellipsis icon > View Entries

**There are two that I was not able to find in UI. Please test these thoroughly**.
1. [select_template.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/select_template.jsp#L37) 
1. [view.jsp ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/browser/view.jsp#L24)

@ambrinchaudhary @jonmak08 @julien

Here is gif of those I was able to find:
after

### CODE REVIEW

**Review by julien — APPROVED** [review]

**Comment by marcelabc** [comment]
Hey @jeyvison could you take a look at this PR, please? Should we let Renato know about this PR?

**Comment by jeyvison** [comment]
Hi @markocikos =D

I'm blocking this one for now until we get the OK from the team that is doing the migration from Metal to React. As soon as they sinalize that everything is fine we can forward it ^^

Thanks for the replacement!

**Comment by natocesarrego** [comment]
ci:test:forms

**Comment by jeyvison** [comment]
ci:help

**Comment by natocesarrego** [comment]
Hey @jeyvison, all reported failures seems to be flaky, please go ahead with this pull. :slightly_smiling_face:

**Review by mateussgn — APPROVED** [review]

**Review by mateussgn — COMMENTED** [review]
LGTM

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
