### PR TITLE
LPS-122358 Document contains at least one immense term in field="ddmFieldArray.ddmFieldValueText_en_US_String_sortable" exception

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
This is a regression caused by [LPS-119088](https://issues.liferay.com/browse/LPS-119088) because that LPS changed the way "sortable" fields are indexed in DDMIndexer, see: https://github.com/jeyvison/liferay-portal/pull/876/files#diff-c98f2b20dea78a52e65c4ea58c98aa96e4d179f73fea2cbf023566fb2578c70fL490-L495
(_note: by mistake, the commits of LPS-119088 are commited with the wrong LPS number LPS-119008_)

**Notes:**
 - I have modified TestOrderHelper to reproduce this issue in both JournalArticle and DLFileEntry, see my first commit [`215ee30` (#16)](https://github.com/liferay-data-engine/liferay-portal/commit/215ee305fd96652a583c1982b37ed241af2f5489)
 - In order to fix the issue I have added the sortable field in the same way it is added in the [_createSortableTextField method of com.liferay.portal.kernel.search.DocumentImpl class](https://github.com/liferay-data-engine/liferay-portal/blob/e035cc567da2b8aba5f511714e052127ef347634/portal-kernel/src/com/liferay/portal/kernel/search/DocumentImpl.java#L1101-L1117), see my change in the commit [`37bd19a` (#16)](https://github.com/liferay-data-engine/liferay-portal/commit/37bd19ab0d266e1c831f7c8eabb2f63bf006f2bf)
 - I have done some additional changes to fix some problems in DDMIndexerTest tests (see commits [`a5821b9`](https://github.com/liferay-data-engine/liferay-portal/commit/a5821b9cf13024ab92a92458d1f0dac9aa7171b7), [`5dfa9bb`](https://github.com/liferay-data-engine/liferay-portal/commit/5dfa9bb757fa39fc97326c2435b0dcc56d41f382) and [`0633482`](https://github.com/liferay-data-engine/liferay-portal/commit/0633482c833b48099903ab038e55c998ccc54e94) )

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Sent to https://github.com/liferay-data-engine/liferay-portal/pull/18

**Comment by jeyvison** [comment]
sent to https://github.com/liferay-data-engine/liferay-portal/pull/19

**Pull request closed without merging**
