### PR TITLE
LPS-124394 Use normalized field label as field reference, Field word is too generic here

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by jeyvison** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@pavel-savinov Could you please fix the js tests?

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:forward

**Pull request closed without merging**
