### PR TITLE
LPS-123183 Add a component that handles the locale changes in the creation of structures

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hi @oliveiraaraujo ! Could you review my PR, please? :)
Thank you

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by jeyvison** [comment]
LGTM!

**Comment by jeyvison** [comment]
ci:forward

**Review by jeyvison — APPROVED** [review]

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
