### PR TITLE
LPS-122358 SF

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
Hi @jeyvison 

I have rebased this PR in https://github.com/liferay-data-engine/liferay-portal/pull/20 to latest master to avoid conflicts in DDMIndexerImpl.java

**Comment by jorgediaz-lr** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/95346

**Pull request closed without merging**
