### PR TITLE
[DE-Migration] LPS-125879 Mock setDataRecord implementation in frontend test because the creation of the dataRecordValues object is not in this module anymore

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-125879

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@jeyvison, could you please ask the AB team to review the changes we've introduced in their modules? More specifically, the last 4 commits. Btw, there's no backend in those commits.

Thanks in advance.

**Comment by tayannasotero** [comment]
@interaminense could you take a look at this PR?

**Comment by rodrigopaulino** [comment]
ci:reevaluate:1052004_7682

**Comment by rodrigopaulino** [comment]
The unique failure seems to be a flaky result. Checking Testray, it's possible to see the same error happening in random builds.

**Comment by interaminense** [comment]
> @interaminense could you take a look at this PR?
> We've introduced some changes in frontend (last 4 commits).

Sure thing. I'll take a look at it on Monday. Thanks @rodrigopaulino @tayannasotero

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by rodrigopaulino** [comment]
forwarded https://github.com/liferay-data-engine/liferay-portal/pull/201

**Pull request closed without merging**
