### PR TITLE
LPS-132789 Make sure that the visibleFields and layout are LocalizedValue objects when deserializing DDMFormField

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-132789

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1027401_695

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Resent in #528

**Pull request closed without merging**
