### PR TITLE
LPS-127978 make sure we are using the same number format as NumericDDMFormFieldValueLocalizer in converter

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-127978

### CODE REVIEW

**Comment by tayannasotero** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
