### PR TITLE
LPS-125791 Selecting the values of a duplicate grid modifies the values of the original grid

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
