### PR TITLE
LPS-128342 Implements value accessor, since in some cases the groupId can be empty

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
@marcosapmf is working on this 👍

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
resent https://github.com/liferay-data-engine/liferay-portal/pull/329

**Pull request closed without merging**
