### PR TITLE
LPS-132279 Fix tests

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-132279

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Probably, some Poshi tests will fail due to changes in labels. We'll wait for the tests results to see what are those.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Hey @rodrigopaulino ,

As we discussed today, I will validate all the types of validations with Luiz tomorrow. Just to be sure that labels still consistent.

Thanks.

**Comment by guilhermedcamacho** [comment]
New PR created #467

**Pull request closed without merging**
