### PR TITLE
[DE-Migration] LPS-125361 SF

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:forward

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
forwarded https://github.com/liferay-data-engine/liferay-portal/pull/97

**Comment by marcosapmf** [comment]
@jeyvison this pull needed to cherry-pick this commit https://github.com/marcosapmf/liferay-portal/pull/285/commits/1788b5aa94efad73f238b62d44cdf5b5ea347843 so I did it and forwarded to #97. In light of this, could you please close this one? 
Thanks :)

**Pull request closed without merging**
