### PR TITLE
LPS-131631 Implement the validation interface for the string validation types

### PR DESCRIPTION
**Pull request by marcelabc**
Today, field validations are hard-coded in the frontend (see [class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/util/validations.es.js)), which doesn't allow developers to extend a validation and create another one.

This work is to provide an extension point in the backend. We are creating an extension in the backend (an interface), so the developer will be able to include new validations (implementing the created interface).

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
@marcelabc - Some of the builds were aborted in this pull request test. I will retest this now. Sorry for any inconvenience.

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
resent https://github.com/liferay-data-engine/liferay-portal/pull/421

**Pull request closed without merging**
