### PR TITLE
LPS-129871 adding a default value for the localizedValue

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-129871

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcosapmf I merged this in manually.

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@marcosapmf I think Brian merged this before the force push, please check the commits in upstream if you haven't already

**Comment by marcosapmf** [comment]
@jpince, I sent him a follow up pull with these new changes.
Thanks

**Comment by jpince** [comment]
@marcosapmf thank you!

**Pull request closed without merging**
