### PR TITLE
LPS-130271 Baseline

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
Hi @boton 
I tried to rebase your work and run the CI again. I believe the CI errors related to the integration tests are happening on master, but I'm not so sure about the Poshi ones (they're flaky with you analyze the PR results in Testray)
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1533287679
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1533430034

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by boton** [comment]
Thank you @marcelabc, I have the same errors in a minimum test PR boton#220 only adding the taglib attribute c1b878b and update the versions ed9d8f0, I remove the usage of the taglib attribute. 

I don´t get the cause of the errors or the relation with only adding a taglib maybe I´m missing something. 

Do you have another idea? Maybe are only flaky tests.

/cc @rodrigopaulino

**Comment by boton** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Taking a look to see if the failures are related, since @marcelabc already reviewed the original PR and made the proper adjustments.

**Comment by rodrigopaulino** [comment]
Hey, @boton. Those failures appear to be related to this PR.
I've checked the first one (`FormRules#ConfigureAutofillRule`) and I've noticed that Data Providers are not being submitted/saved after the inclusion of this flag. Could you please make sure these changes don't affect other products that use the same logic?

I'm closing this as "changes required".

Kind regards.

**Pull request closed without merging**
