### PR TITLE
LPS-131479 Check if company id is not iquals to structure group id

### PR DESCRIPTION
**Pull request by choliveira84**
https://issues.liferay.com/browse/LPS-131479

### CODE REVIEW

**Comment by choliveira84** [comment]
@danvb112 I sent this commit with the fix. Check it out.

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
Hey @choliveira84 ,

Could you fix the source format issue?

Thanks!

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
@choliveira84 , I found the issue for you, the problem is that "commit message is pointing to non-existing JIRA issue: LPS-134179"

In the relevant's result above, you can click on "For more details click [here]"(https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/5857/jenkins-report.html), then click on Console link below "Top Level Build - FAILURE". If you scroll down through the log you will see the message below:

`format-source-files:
     [java] java.lang.Exception: Commit message is pointing to non-existing JIRA issue: LPS-134179
     [java] 	at com.liferay.source.formatter.util.JIRAUtil.validateJIRATicketIds(JIRAUtil.java:165)
     [java] 	at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1189)
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:355)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:312)`

**Comment by choliveira84** [comment]
> @choliveira84 , I found the issue for you, the problem is that "commit message is pointing to non-existing JIRA issue: LPS-134179"
> 
> In the relevant's result above, you can click on "For more details click [here](https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/5857/jenkins-report.html)", then click on Console link below "Top Level Build - FAILURE". If you scroll down through the log you will see the message below:
> 
> `format-source-files: [java] java.lang.Exception: Commit message is pointing to non-existing JIRA issue: LPS-134179 [java] at com.liferay.source.formatter.util.JIRAUtil.validateJIRATicketIds(JIRAUtil.java:165) [java] at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1189) [java] at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:355) [java] at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:312)`

my bad...

**Comment by choliveira84** [comment]
ci:test:sf

**Comment by choliveira84** [comment]
ci:test:relevant

**Comment by choliveira84** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Hey @choliveira84 ,

As we talked now together with @marcelabc , I will wait you to debug the code and understand better how these links between sites, structures and field sets works, so we can move on with more confidence.

If you have any doubts please contact us.

Thanks!

**Comment by guilhermedcamacho** [comment]
Further investigation is required, so the sender will need to submit a new pull request later.

**Pull request closed without merging**
