### PR TITLE
LPS-127602 PortletNamespace is sometimes not present

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @liferay-data-engine!

Please read my commit message: https://github.com/liferay-data-engine/liferay-portal/pull/239/commits/556f1298718b1af71ce1aca5030f46cb334cc66c.

I'm fixing the issue but I am not sure if that's the right way.

Thanks!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just rebase and push forced.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-data-engine/liferay-portal/pull/267

**Pull request closed without merging**
