### PR TITLE
LPS-132794 Autofill the visible fields with the selected address

### PR DESCRIPTION
**Pull request by EliveltonR18**
This PR depends on this one to be merged:

[LPS-132793](https://github.com/liferay-data-engine/liferay-portal/pull/526)

Related issue: https://issues.liferay.com/browse/LPS-132794

### CODE REVIEW

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
