### PR TITLE
LPS-125439 Adds code to handle checkbox multiple with only one element to make it compatible with old versions

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
I'm going to fix the broken tests

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
@ealonso LGTM!

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
