### PR TITLE
LPS-124616 override onInstanceReady event callback

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-124616

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
Hey @marcosapmf since we are modifying the ClassicEditor component it is good to send it to the user of Frontend Infra to evaluate.

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by marcosapmf** [comment]
forwarded to https://github.com/liferay-frontend/liferay-portal/pull/607

**Pull request closed without merging**
