### PR TITLE
LPS-129131 - NPE occurs on JournalSubscriptionClassTypeTest#testSubscriptionClassTypeWhenUpdatingBaseModel

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @marcelabc

When testing locally make sure to start server with `mail.send.blacklist=` in portal-ext.properties.

This property is set in /liferay-portal/portal-impl/test/portal-test.properties and is required for the test to work.

### CODE REVIEW

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Hi @marcosapmf!

When running the test on hash 8cf1bfb038cd, which contains the commit in https://github.com/liferay-data-engine/liferay-portal/pull/324, I get a NPE on:
`DDMFormValuesToFieldsConverterImpl.setDDMFieldValue(DDMFormValuesToFieldsConverterImpl.java:202`

The test runs successfully for me locally with the commit included on this PR on top of 8cf1bfb038cd.

Besides including `mail.send.blacklist=` I start the portal with `export CATALINA_OPTS=\"-Dliferay.mode=test\"; ../bundles/tomcat-9.0.43/bin/catalina.sh start;`

I see the NPE in testray as well: https://testray.liferay.com/home/-/testray/case_results/1508036724/history?testrayCaseId=1310762910&testrayRoutineId=1306753888&cur=1&delta=200&environmentHash=-1335676998&hideFilterPin=true&resetCur=false&tab=result&orderByCol=errors_sortable&orderByType=asc

Which corresponds to the stacktrace I observe when running the test locally:
```
com.liferay.portal.kernel.search.SearchException: java.lang.NullPointerException
	at com.liferay.portal.kernel.search.BaseIndexer.getDocument(BaseIndexer.java:180)
	at com.liferay.journal.internal.search.JournalArticleIndexer._reindexEveryVersionOfResourcePrimKey(JournalArticleIndexer.java:1006)
	at com.liferay.journal.internal.search.JournalArticleIndexer.doReindex(JournalArticleIndexer.java:617)
	at com.liferay.journal.internal.search.JournalArticleIndexer.doReindex(JournalArticleIndexer.java:117)
	at com.liferay.portal.kernel.search.BaseIndexer.reindex(BaseIndexer.java:544)
	at com.liferay.portal.search.IndexableAdvice.afterReturning(IndexableAdvice.java:137)
	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:66)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy924.updateArticle(Unknown Source)
	at com.liferay.journal.service.JournalArticleLocalServiceUtil.updateArticle(JournalArticleLocalServiceUtil.java:3858)
	at com.liferay.journal.test.util.JournalTestUtil.updateArticle(JournalTestUtil.java:947)
	at com.liferay.journal.test.util.JournalTestUtil.updateArticle(JournalTestUtil.java:895)
	at com.liferay.journal.test.util.JournalTestUtil.updateArticle(JournalTestUtil.java:855)
	at com.liferay.journal.test.util.JournalTestUtil.updateArticle(JournalTestUtil.java:884)
	at com.liferay.journal.test.util.JournalTestUtil.updateArticleWithWorkflow(JournalTestUtil.java:975)
	at com.liferay.journal.subscriptions.test.JournalSubscriptionClassTypeTest.updateBaseModel(JournalSubscriptionClassTypeTest.java:129)
	at com.liferay.subscription.test.util.BaseSubscriptionClassTypeTestCase.testSubscriptionClassTypeWhenUpdatingBaseModel(BaseSubscriptionClassTypeTestCase.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.liferay.dynamic.data.mapping.internal.util.DDMFormValuesToFieldsConverterImpl.setDDMFieldValue(DDMFormValuesToFieldsConverterImpl.java:202)
	at com.liferay.dynamic.data.mapping.internal.util.DDMFormValuesToFieldsConverterImpl.createDDMField(DDMFormValuesToFieldsConverterImpl.java:151)
	at com.liferay.dynamic.data.mapping.internal.util.DDMFormValuesToFieldsConverterImpl.addDDMField(DDMFormValuesToFieldsConverterImpl.java:78)
	at com.liferay.dynamic.data.mapping.internal.util.DDMFormValuesToFieldsConverterImpl.addDDMFields(DDMFormValuesToFieldsConverterImpl.java:100)
	at com.liferay.dynamic.data.mapping.internal.util.DDMFormValuesToFieldsConverterImpl.convert(DDMFormValuesToFieldsConverterImpl.java:60)
	at com.liferay.dynamic.data.mapping.internal.util.DDMIndexerImpl.toFields(DDMIndexerImpl.java:734)
	at com.liferay.dynamic.data.mapping.internal.util.DDMIndexerImpl.addAttributes(DDMIndexerImpl.java:110)
	at com.liferay.journal.internal.search.JournalArticleIndexer.addDDMStructureAttributes(JournalArticleIndexer.java:333)
	at com.liferay.journal.internal.search.JournalArticleIndexer.doGetDocument(JournalArticleIndexer.java:531)
	at com.liferay.journal.internal.search.JournalArticleIndexer.doGetDocument(JournalArticleIndexer.java:117)
	at com.liferay.portal.kernel.search.BaseIndexer.getDocument(BaseIndexer.java:152)
	... 46 more
```

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1067401_8157

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
I'm discarding the PR since the issue is no longer reproducible in today's master dfa20979364a8, and the test is no longer failing in [testray](https://testray.liferay.com/home/-/testray/case_results/1508036724/history?tab=result&hideFilterPin=true)

Screenshot 2021-03-18 at 10 28 57

**Comment by marcosapmf** [comment]
Hey @ruben-pulido, 
Since the error is not occurring anymore, I go ahead and close this pull.

Thanks a lot for your help

**Pull request closed without merging**
