### PR TITLE
LPS-132723

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
Forward https://github.com/liferay-data-engine/liferay-portal/pull/563

https://issues.liferay.com/browse/LPS-132723

It can be difficult for the user to use the web content toolbar options if the text is very long. This was verified as a bug in this comment: https://issues.liferay.com/browse/PTR-2478?focusedCommentId=2462821&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2462821

This is resolved by having "resize_enabled", true and disabling autogrow plugin for the editor. In order to do this, I had to create JournalArticleContentEditorConfigContributor to edit the Web Content and edit JournalArticleDescriptionEditorConfigContributor. I was able to check this change resolves the issue.

Let me know if there are any questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — APPROVED** [review]
LGTM 🎉 

Hey @ealonso, I see there are editions from the Journal side, do you want to review them? 😄

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @marcelabc,

LGTM!!

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@fortunatomaldonado, the failure reported by CI is consistent and appears to be related to your changes. Have you tried creating a new Structure with a Rich Text, instead of only testing with the Basic Web Content?

I'm signalling this pull as changes required. 
Thanks for looking into this.

**Comment by rodrigopaulino** [comment]
I'm closing this PR. Please send a followup pull with the required changes.

Thx in advance.

**Pull request closed without merging**
