### PR TITLE
[DE-Migration] LPS-125380 Getting localizedValue from field.

### PR DESCRIPTION
**Pull request by oliveiraaraujo**

### CODE REVIEW

**Comment by oliveiraaraujo** [comment]
ci:test:sf

**Comment by oliveiraaraujo** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
LGTM!

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
