### PR TITLE
LPS-125531 Avoid recreating debounce callback on every call

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hi! This is a follow up for https://github.com/liferay-data-engine/liferay-portal/pull/151 (that was closed because of rebase error). After trying some other options suggested by @matuzalemsteles [here](https://github.com/liferay-data-engine/liferay-portal/pull/151#discussion_r561942879), I didn't found any other solution that doesn't lead to getting stale properties into createField callback.

These are the options I tried:

```js
const fieldChange = (opts) => (dispatch) => () => { /* ... (no debounce) ... */ }

const Layout () => {
  const createFieldChange = useEvaluate(fieldChange);
  // Debounce is created only on first render, which make the createFieldChange function rely
  // on the opts that existed on first render
  const debouncedCreateFieldChange = useMemo(() => debounce(createFieldChange), []);
}
```

```js
const useDebounce = (fn) => useCallback((args) => debounce(fn(args)), []);
const fieldChange = (opts) => (dispatch) => () => { /* ... (no debounce) ... */ }

const Layout () => {
  // Debounce wraps fieldChange, but not createFieldChange. This gives
  // updated opts to createFieldChange, but debounce is not being applied
  // to the function being executed, only to the declaration
  const createFieldChange = useEvaluate(useDebounce(fieldChange));
}
```

I am not happy creating a custom hook only for this use case, but maybe we could inline it inside Layout.es.js, as this is not being used anywhere else. The main "issue" (headache) here is the property injection performed by useEvaluate. Maybe trying to make a debounce inside useEvaluate somehow could lead to a solution, but that will be applied to all useEvaluate usages.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Hey @p2kmgcl hmm what a pity it didn't work as expected! 🤔 I'm fine with creating a `useDebounceEvaluate` with `debounce` to avoid losing the reference. In case it still doesn't work I think we can go with the creation of the `useCreateFieldChange` hook and let's see if we can remove the use of `debounce` later.

**Comment by p2kmgcl** [comment]
Hey @matuzalemsteles, I just found that this `useDebounceEvaluate` doesn't work:

```js
export const useDebounceEvaluate = (thunk, delay = DEFAULT_DELAY_MS) => {
	const {
		defaultLanguageId,
		editingLanguageId,
		groupId,
		pages,
		portletNamespace,
		rules,
	} = usePage();

	const debouncedThunk = useMemo(() => {
		return debounce(thunk, delay);
	}, [thunk, delay]);

	return useCallback(
		(args) =>
			debouncedThunk({
				defaultLanguageId,
				editingLanguageId,
				groupId,
				pages,
				portletNamespace,
				rules,
				...args,
			}),
		[
			defaultLanguageId,
			editingLanguageId,
			groupId,
			pages,
			portletNamespace,
			rules,
			debouncedThunk,
		]
	);
};
```

```js
export default function fieldChange({
	defaultLanguageId,
	editingLanguageId,
	groupId,
	pages,
	portletNamespace,
	properties,
	rules,
}) {
	return (dispatch) => () => { /* ... */ }
}
```

```js
const createFieldChange = useDebounceEvaluate(fieldChange)
```

And this is why: if you debounce fieldChange fn, you get debouncedCreateFieldChange, which returns no value when being executed because it is being debounce, so the thunk dispatch crashes because there is no thunk. We need this:
```js
(dispatch) => debounce(() => { /* ... */ }) // -> returns () => void
```
and we get this:
```js
debounce((dispatch) => () => { /* ... */ }) // -> returns void
```

At this point, I don't see a more beautiful solution so, if you don't have any other suggestion, I think we can move this PR.

**Comment by matuzalemsteles** [comment]
Hey @p2kmgcl, yeah makes sense. Well, then having debounce is a big problem. So let's go with your initial hook implementation for this. I'll see if we can remove this debounce during the migration. Thank you very much @p2kmgcl for evaluating other alternatives.

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
