### PR TITLE
LPS-132212 Fieldset links are duplicated on the Propagation and Delete dialogs

### PR DESCRIPTION
**Pull request by EliveltonR18**
This changes are for add the property `id` in:

- `DataDefinitionSchema`
- `DataLayoutSchema`

This property is used in `usePropagateFieldSet.es.js` for filter the [dataLayout](https://github.com/liferay/liferay-portal/blob/6e25ad1e3cdcd4c6657caad6adef34ec3fbd64c6/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/components/field-sets/actions/usePropagateFieldSet.es.js#L89) and [dataDefinition](https://github.com/liferay/liferay-portal/blob/6e25ad1e3cdcd4c6657caad6adef34ec3fbd64c6/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/components/field-sets/actions/usePropagateFieldSet.es.js#L80).

The changes in `usePropagateFieldSet.es.js` fix the bug of the duplicate links in dialog. Some changes in this file too are for delete unnecessary code.

Beyond this, was deleted two legacy files that are not being used:

- `FieldSets.es.js`
- `FieldSetModal.es.js`

For not crash the frontend test suite, the tests of the `FieldSets.es.js` was skipped and need to be rewritten.

Related issue: https://issues.liferay.com/browse/LPS-132212

### CODE REVIEW

**Comment by EliveltonR18** [comment]
ci:test:sf

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:stop

**Comment by EliveltonR18** [comment]
ci:stop

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by EliveltonR18** [comment]
ci:test:sf

**Review by miltonmc — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by miltonmc** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Rerunning relevant because it appeared to have failed during the buildService task, which is not related to this pull.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:forward

**Pull request closed without merging**
