### PR TITLE
LPS-133741 "There was an error when loading the "rich_text" field." display after translating to both ES and JP

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-133741

Sometimes the CKEditor instance isn't ready and we try to call the resetUndo.

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
Hey @boton , 

Could you fix semantic versioning problem reported in relevant test?

Thanks!

**Comment by boton** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_924

**Comment by boton** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
