### PR TITLE
LPS-125540 Set property in jsp

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hi @victorg1991  :)

I think we don't need a taglib parameter for this one. The behavior should be the same when the fix is applied for everyone, **but** we cant remove **<AutoFocus>** because it's needed to focus in the first field when the layout is rendered.

Let me know if you need more info :)

**Comment by victorg1991** [comment]
@jeyvison For the web content app is it not needed at all (I've checked this with our designer). But I need to pass something to the component to disable it in some cases, how do you think this can be achieved without the taglib param?

**Comment by victorg1991** [comment]
I undertand that other cases like forms/app builder and so on needs this autofocus feature, that is why I am not sure how to disable it only on web content without adding a parameter

**Comment by victorg1991** [comment]
@jeyvison Do you know what the autofocus is used for? From my investigations it was added to be able to scroll to the first field when changing the page. If it is only that I think another easy solution would be to only autofocus when the structure has more than one page. What do you think?

**Comment by jeyvison** [comment]
Hey @victorg1991 ! Sorry for the delay in answering you. I was talking with Luiz (our PM) about the desired behavior.

Turns out that the only place this focus is expected to be working as it is now is in Forms, so we could try to move this flag  to Forms taglib.

So i think the solution would be something like:

- Move the flag to DDMFormRendererTag with the name "EnableAutoFocus"
- Keep the logic how it is now in your PR (changing the variable name where applicable)

Let me know what you think about it

**Comment by victorg1991** [comment]
Got it @jeyvison 

I'll let you know if some question arises 👍 
Thank you!

**Comment by victorg1991** [comment]
Closing this for now

**Pull request closed without merging**
