### PR TITLE
LPS-133884 Change parameter name

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-133884

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@marcelabc, to give you more context of these changes I've made. During code review, I thought we were too much bound to where the `indexType` setting was positioned in the layout (something that slipped my mind during refinement meeting). Imagine that our PM plans to introduce a new page between the Basic and Advanced... that solution we came up with would stop working, thus causing a regression.

Hope you understand the refactoring.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Best to wait this version to updated on master before running the relevant suite again.

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Resent in #525

**Pull request closed without merging**
