### PR TITLE
LPS-134038 Add missed and remove extra values correctly

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-134038

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Unit test failing, I'll take a look and make the necessary modifications.

**Comment by rodrigopaulino** [comment]
@mateussgn, I'm closing this PR because we no longer review pull requests from Engineering, only from Support. Could you please send a new one to @natocesarrego's repo and change the ticket assignee to him?

Thx in advance.

**Comment by mateussgn** [comment]
Sure, I'll send it to him! Thanks @rodrigopaulino

**Pull request closed without merging**
