### PR TITLE
LPS-115153 Changing alert size

### PR DESCRIPTION
**Pull request by mateussgn**

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by mateussgn** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
