### PR TITLE
[DE-Migration] LPS-125349 We should set the data type for date and geolocation, since we need the data type when we are getting the template on DDMTemplateVariableCodeHandler see:

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
LGTM!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Review by d80wrk — COMMENTED** [review]
"Adds logic to upgrade boolean to checkbox_multiple"

Doh!

- [ ] Task One, review basic computer logic class

**Pull request closed without merging**
