### PR TITLE
LPS-128158 Don't validate that options is translated for all the languages since it is not required. As other localized values, having the default language translation is enough

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by marcelabc** [comment]
Hi @victorg1991 😄 
I had to block this PR from forwarding because your solution was not ideal. Your commit message's content is right, but and you are trying to avoid the use of "validateDDMFormPropertyValue," but we really should use it.

DDMFormValidatorImpl is used for many projects. We should not change the way of validating the field properties.
I know that Data Engine has this new rule of not obligating the translation for all languages, but there are projects that this is still the valid rule.

Our team had a solution to catch the exception in another class, inside the DE module, and avoid this case from happening. I just found out that this was refactored, and I have to talk with the dev to understand his needs.

I will be responsible for this LPS from now on, okay?
Thank you for your work!! Let me know if you have any questions.

**Comment by victorg1991** [comment]
Hey @marcelabc !

I read the comments and find a another way to do it, so I've given another try, I've used the same approach used for other properties :) Let me know what do you think

Thanks! :)

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Hi @victorg1991 ,
Thank you for the work! It's really nice, I will forward to Brian 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
