### PR TITLE
[DE-Migration] LPS-125084 Rename

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-125084

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
@rodrigopaulino LGTM! You can forward it as soon as the tests finish running

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
