### PR TITLE
LPS-125029 Delete doAsGroupId from the URL if the container is a nested html field

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

This applies https://github.com/liferay-data-engine/liferay-portal/pull/45 for nested HTML fields as well.

Thank you and best regards,
István

### CODE REVIEW

**Comment by jeyvison** [comment]
Hey @oliveiraaraujo , can you please review this one?

**Comment by IstvanD** [comment]
Dear @oliveiraaraujo, 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Review by oliveiraaraujo — APPROVED** [review]
LGTM!

**Comment by jeyvison** [comment]
ci:forward

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
