### PR TITLE
LPS-130342 dynamic-data-mapping-api: baseline

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-130342

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi, is there any update on this? There is a customer waiting for the fix, I was wondering if you see it safe to provide them with the changes made here (or similar ones, since they are in 7.2).
Thanks

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
Hi @crodriguezy, how are you doing?
I noticed that the ticket behavior happens on master and 7.2.x. However, there is a difference between the 2 versions: the taglib used. On master, Web Content uses Data Engine Taglib. On 7.3.x and the previous version, Web Content uses DDM taglib. This PR is solving the code on master, and I cannot guarantee that this solution is safer for the 7.2.x because the code can be different since the Taglib's are different.
I would advise you to look for the solution in the 7.3.x because it seems that the code could be more adequate for the 7.2.x version. 

If you need help to do this task, feel free to reach us (Data Engine team) again 😃  (you can open a PTR as well)
Thank you!

**Comment by crodriguezy** [comment]
Hello @marcelabc ,

Finally I've been able to find the solution for 7.2.x, based on the actual code of 7.3.x, which still uses the DDM taglib. Thank you and  @guilhermedcamacho for the support :)

**Comment by guilhermedcamacho** [comment]
Pushed a new branch to resolve conflicts. New Pr here: #410

**Pull request closed without merging**
