### PR TITLE
[DE-Migration] LPS-125369 convert title json object into map

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-125369

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
@marcosapmf LGTM!

**Review by jeyvison — APPROVED** [review]

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:stop

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
