### PR TITLE
LPS-155021 Add condition for fieldset label

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-155021

When a field is nested inside a `fieldset` and the user changes the language, the field's translation will be set to the translation of the `fieldset`, rather than its original translation. 
This is occurring since the `setLabel` looks for `instance.getLabelNode();`. This will result in getting the `field` information when the instance is the `fieldset`. The `field` will then be translated into the `fieldset` information.

In order to resolve this, I included a condition that will check if the type is a `fieldset` and correctly translate it.

Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
Hi @fortunatomaldonado, how are you doing?

The Data Engine Team and Forms Team are now a single team, so, from now on, all pull requests targeting Data Engine Team should be sent to the GitHub user @liferay-forms. 

Could you resend this PR to the @liferay-forms, please?

Sorry for the inconvenience.

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
