### PR TITLE
[DE-Migration] LPS-125879 Add javadoc

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket: https://issues.liferay.com/browse/LPS-125879

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:app-builder

**Comment by rodrigopaulino** [comment]
ci:test:lima

**Comment by rodrigopaulino** [comment]
ci:test:tango

**Comment by rodrigopaulino** [comment]
ci:test:forms

**Comment by sandrodw3** [comment]
After testing this PR, I can confirm it also fixes https://issues.liferay.com/browse/LPS-126709 🙂, so waiting for this to be merged to close that ticket.

**Comment by veroglez** [comment]
This PR also fixes https://issues.liferay.com/browse/LPS-126161, so I’m closing https://github.com/liferay-data-engine/liferay-portal/pull/176 and waiting to close that ticket

**Comment by rodrigopaulino** [comment]
ci:test:echo

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by rodrigopaulino** [comment]
Closing as this has tests to fix.

**Comment by marcosapmf** [comment]
forwarded https://github.com/liferay-data-engine/liferay-portal/pull/178

**Pull request closed without merging**
