### PR TITLE
LPS-132436 Remove usage and definition of the no-longer-used isShowStructureSelection

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hi @liferay-data-engine & specifically @rafaprax! 👋 

Resending as directed in https://github.com/liferay-workflow/liferay-portal/pull/391#issuecomment-852993199

This is a PR that removes `isShowStructureSelection` which is apparently dead code. I wanted to migrate the `openDDMPortlet` but @rafaprax warned me it's probably dead code.

I've removed the usages and definitions, and tested and everything checks out fine.

# 🧪 Testing
1. Make sure you have access to Kaleo Forms Admin
2. Start creating a new Process
3. On Forms step create a new Form and assign it to the Task

### CODE REVIEW

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hi, @kresimir-coko 
First of all, thanks for contributing. :)

I've noticed that you deleted an API method. Could you please avoid breaking changes?

Best.

**Comment by kresimir-coko** [comment]
> I've noticed that you deleted an API method. Could you please avoid breaking changes?


@rodrigopaulino thanks, I'm very inexperienced with Java so that's probably why 😄 

Gonna remove that change, and push again.

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @choliveira84. I'm requesting @guilhermedcamacho's review since I'm not going to be able to get back to this today.

**Comment by choliveira84** [comment]
Hey, @kresimir-coko , the relevant have failed. Could you check?

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
ci:forward

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Pull request closed without merging**
