### PR TITLE
LPS-128915 simplify

### PR DESCRIPTION
**Pull request by marcosapmf**
Related ticket: https://issues.liferay.com/browse/LPS-128915

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Rebasing...

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
It's causing errors in functional tests.

**Pull request closed without merging**
