### PR TITLE
LPS-127462 update test constant

### PR DESCRIPTION
**Pull request by marcosapmf**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Already reviewed [here](https://github.com/liferay-data-engine/liferay-portal/pull/372)

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Investigating the consistent failure.

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-data-engine/liferay-portal/pull/384

**Pull request closed without merging**
