### PR TITLE
LPS-125511 We can receive both string or object as inputValue

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hello @victorg1991 :) 

Can you please check the error in the integration test? The **if** block you introduced is falling in the same case as the **else**. Since the value is not a object array, it must be a Map and we are treating the value as a Map inside the **else** code.

**Comment by victorg1991** [comment]
Closing this as this pr is solving the same thing https://github.com/liferay-data-engine/liferay-portal/pull/118
The second commit will be sent separately

**Pull request closed without merging**
