### PR TITLE
LPS-128585 Pass the defaultLanguage of the document to the dataLayoutRender and update the defaultLanguage input

### PR DESCRIPTION
**Pull request by victorg1991**
Hey!

If you find some problems when changing the configuration, you may be able to redeploy the journal-web module and update the config again. I'm still investigating this but it is not related to the pr

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — APPROVED** [review]
LGTM

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Looks that the poshi test failures are legit, trying to find out what is happening

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
should be fine now

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
