### PR TITLE
LPS-129763 Return parsed value if it is an image field

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-129763

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
LGTM

**Review by rodrigopaulino — APPROVED** [review]

**Comment by jpince** [comment]
@mateussgn thank you! If the tests finish after your day is over, can this PR be forwarded to Brian?

**Comment by tayannasotero** [comment]
Yes, @jason! The guys put a label good-to-go!

**Comment by mateussgn** [comment]
Sure @jpince !

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by mateussgn** [comment]
Directly sent to @brianchandotcom 
https://github.com/brianchandotcom/liferay-portal/pull/100332

**Pull request closed without merging**
