### PR TITLE
LPS-127673 Return option with id when it is edited

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
LGTM

**Review by marcosapmf — APPROVED** [review]

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Hey @veroglez ! 
Sorry for the delay, I was investigating this PR's test failures, and I just discovered that another bug fixed this issue by the forms team! I will close this PR, okay?
Thank you for your work 😄

**Pull request closed without merging**
