### PR TITLE
LPS-132436 Remove unnecessary selectEntityHandler

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hi @liferay-data-engine, this is a small PR to finish off this task. It just removes the leftover `selectEntityHandler` usage that is obsolete with the switch to `openSelectionModal`.

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1257401_920

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
