### PR TITLE
Lps 130720

### PR DESCRIPTION
**Pull request by SamZiemer**
Tests passed here: https://github.com/SamZiemer/liferay-portal/pull/799#issuecomment-821589255

Notes from @brianikim:

> https://issues.liferay.com/browse/LPS-130720
> 
> Straightforward issue here. We are updating to version 2.4.2 for both accessors-smart and json-smart jars per security issue reported in LPS-130720

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
test results look good. Please let me know if there's anything that needs to be addressed.

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
