### PR TITLE
LPS-128060 Add a hidden input instead of using the one included in clay as it is occupying extra space

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
fixing the tests!

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
