### PR TITLE
LPS-131638 Integration tests

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-131638

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
This should wait for https://github.com/liferay-data-engine/liferay-portal/pull/437 to be merged first.

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
This is no longer blocked since the dependant pull request is already merged.

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
