### PR TITLE
LPS-127978 Not force integer type in replaced languages

### PR DESCRIPTION
**Pull request by boton**
Trying not to do operations on the replaced language numbers is the only thing I can think of, but it still doesn't work well.

On the other hand, I have no idea where the transformations from numbers in English to numbers in Arabic occur nor if there are other languages that suffer these replacements.

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
Hi @boton , I blocked this pull because we are going to talk to our product manager about if we really should translate numbers in Numeric field to arabic or any other language.
I'll come back to this pull as soon as we have aligned this behavior with him
Thanks

**Comment by marcosapmf** [comment]
Hi, @boton
Sorry about the late. After talking to our product owner about this issue, we decided to not allow the number field being translated to arabic and let it with the same behavior than the previous versions. In light of this, I'm closing this pull and going to work on it.

Thank you for all your effort

**Pull request closed without merging**
