### PR TITLE
LPS-128056 return the value as it is when it is a number that is bigger than max valid number

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-128056

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Comment by rodrigopaulino** [comment]
Hey, @marcosapmf. Could you please check the comment I've made in the ticket? Thanks.

**Pull request closed without merging**
