### PR TITLE
[TS | Master] LPS-134087 Avoiding incorrect focus in a form field

### PR DESCRIPTION
**Pull request by rijema**
Click [here](https://issues.liferay.com/browse/LPS-134087) to see the LPS

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hi, @rijema.

Pull request reviews might be delayed due to changes in internal processes. We'll let you know here when the review starts.

Thanks for contributing.

**Comment by rijema** [comment]
Hi @rodrigopaulino,

Thank you for letting me know.

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
