### PR TITLE
LPS-131844 Change path to DataEngineLayoutBuilderHandler

### PR DESCRIPTION
**Pull request by danvb112**
Related issue: https://issues.liferay.com/browse/LPS-131844

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
