### PR TITLE
LPS-148748 Add Intergration test

### PR DESCRIPTION
**Pull request by SamZiemer**
Adding integration test for [LPS-148748](https://issues.liferay.com/browse/LPS-148748)

/cc @quanhuynhces

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
Hi @SamZiemer @quanhuynhces, how are you doing?

We ended up missing this PR because all pull requests targeting Data Engine component are now sent to GitHub user @liferay-forms.

If you still think it's worth it, could you resend this PR to the @liferay-forms?

Sorry for the inconvenience.

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
