### PR TITLE
LPS-132279 Fix the validations templates

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@marcelabc, the integration test needs to be updated as well. :)

**Comment by marcelabc** [comment]
We must wait for the https://github.com/brianchandotcom/liferay-portal/pull/102026 to be merged and sync to run the CI to verify the results 👍

**Comment by marcelabc** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
This needs changes.

**Pull request closed without merging**
