### PR TITLE
LPS-132015 Pass required error message through context

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-132015

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Wait for https://github.com/liferay-data-engine/liferay-portal/pull/448 to be merged before rerunning the relevant suite.

**Comment by rodrigopaulino** [comment]
The failure actually looks unrelated. Running the suite again.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
