### PR TITLE
LPS-129091 asset-list-service: no reason for using the classTypeId when there is no structure id to form the ddmFieldName attribute

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-129091

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
The CI failure reported by the last run of the relevant suite is already happening on other pulls. See https://github.com/liferay-data-engine/liferay-portal/pull/377#issuecomment-811484545

**Comment by marcosapmf** [comment]
Hey @rodrigopaulino ,
this pull looks good to me, I just would like your help to show me how I can see it working

**Comment by rodrigopaulino** [comment]
> Hey @rodrigopaulino ,
> this pull looks good to me, I just would like your help to show me how I can see it working

Sure thing, @marcosapmf. You basically need to test the impacted products and check if they still work as expected, even with the index change. To check the index change, you can see the ticket's description on which I wrote how it was before and how it should be. Also, you can use elasticsearch-head if you want to access the index by using a web interface. Hit me up on Slack in case you need some assistance with any of these steps.

Thanks for reviewing this!

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
