### PR TITLE
[DE-Migration]LPS-125361 pass default locale from data layout builder to form provider

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-125361

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
resent. See https://github.com/liferay-data-engine/liferay-portal/pull/88

**Pull request closed without merging**
