### PR TITLE
LPS-131638 Integration tests

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-131638

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
Blocked because it must wait for https://github.com/liferay-data-engine/liferay-portal/pull/431 to be merged first.
To the reviewer: I stopped the relevant suite because, without the PR aforementioned, it will fail. Please rerun when there's no dependency.

**Comment by marcelabc** [comment]
Blocked because it must wait for liferay-data-engine#431 to be merged first.

**Comment by rodrigopaulino** [comment]
Will be sending another one, since we decided to change this logic.

**Pull request closed without merging**
