### PR TITLE
LPS-12337 fix poshi test

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-122337

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:stop

**Pull request closed without merging**
