### PR TITLE
LPS-122340 Create a way to reference DDM field attributes from the database

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by jeyvison** [comment]
ci:test:forms

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Fixed rebasing. See: https://github.com/liferay-data-engine/liferay-portal/pull/38

**Pull request closed without merging**
