### PR TITLE
[DE-Migration] LPS-125685 remove fieldset tab from sidebar in fieldset modal as a default behavior

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-125685

### CODE REVIEW

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
