### PR TITLE
LPS-126019 It's possible to save fields that have options without any options for a fieldset

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by jeyvison** [comment]
hi @veroglez  :) Thanks for your fix =D

We already have this kind of check in backend for the fields that are not in fieldset. Check `DataDefinitionValidationException.MustSetOptionsForField` exception in `data_layout_builder/end.jsp`.

Could we try to use the same backend logic and apply it to fieldsets?

**Review by mateussgn — COMMENTED** [review]
LGTM

**Comment by veroglez** [comment]
Hi @jeyvison! I’ve been looking if the same backend logic for fields can be used for fieldsets. To use this logic, all that I've done is convert the localized value of each option to an empty array if they are not edited. However, I’m not sure if the error is exactly what we want to show, since in this case a generic error appears and the modal is closed. 

Could you take a look at it and check if this should be the case? Or would it be more appropriate if a specific error message appears and the modal did not close?

**Comment by ealonso** [comment]
Hey @jeyvison,
Could you please take a look to @veroglez comment? https://github.com/liferay-data-engine/liferay-portal/pull/170#issuecomment-771451048
Thanks!
Eudaldo

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Hey @jeyvison,
I don't believe that letting this validation to the backend a good idea because the modal is closed brutally. Please, see this video:

https://user-images.githubusercontent.com/15161924/106953531-44203b00-6711-11eb-8665-1ad388048762.mp4

If this case were about this error not involving the modal, I would agree with you. I believe that the modal is "more difficult" to control and to leave it opened after the validation goes to the backend. Would you think that it would be better/easy to validate this on the frontend side? So the modal would be left open and display the error message inside it.

Besides that, I've talked with Emanuel(QA) and the behavior expected is to let the modal opened and show the error message. This behavior prevents the loss of the structure and its fields.

**Comment by jeyvison** [comment]
@marcelabc @veroglez . Got it. I understand the behavior now. It really would be better if the modal didn't close and we show an specific error message.

@veroglez Sorry for the delay in answering you ^^

**Comment by marcelabc** [comment]
Hi @veroglez !
What is your opinion about this? Was your first solution according to the expected result? 

> Besides that, I've talked with Emanuel(QA) and the behavior expected is to let the modal opened and show the error message. This behavior prevents the loss of the structure and its fields.

**Comment by veroglez** [comment]
Hi @marcelabc and @jeyvison!
Yes, my first solution showed a specific error and did not close the modal. I have updated the code for this solution. Can you check if it is the correct solution?

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
@veroglez LGTM! Thanks a lot Veronica!

**Review by jeyvison — APPROVED** [review]

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevantci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hi @veroglez :) I think a test fix will be needed for at least LocalFile.SharedAppBuilder#DeleteFormViewFieldFromObject. Could you please take a look ? If you need help you can talk with Guilherme Freire at slack, he is app builder's QA.

Thanks a  lot!

**Comment by veroglez** [comment]
Hi @jeyvison, I will take a look, thank you!

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
Resent her https://github.com/liferay-data-engine/liferay-portal/pull/226

**Pull request closed without merging**
