### PR TITLE
LPS-132793 Added usePlaces hook to attach powered by google dropdown

### PR DESCRIPTION
**Pull request by EliveltonR18**
Related issue: https://issues.liferay.com/browse/LPS-132793
Resending #523

### CODE REVIEW

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
