### PR TITLE
LPS-133831 fix upgrade values changing them to the actual values that the DERendered read correctly. #1934

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-133831 The Number and Boolean fileds value changes after upgrade

The value of the old boolean changed from checkbox to checkbox_multiple, so now we need to search the *%checkbox%* fields.

On the other hand, the values of the numeric fields needed to be formatted to values without the thousand separator (and depending of the locale)

on the commit https://github.com/liferay-data-engine/liferay-portal/pull/518/commits/cce1777a242032e84b0e6e67c7b9c31646df7521 I tested what happened if launched both and seem that is no longer needed and the second fixes that the first can not update.

Thanks!

### CODE REVIEW

**Comment by choliveira84** [comment]
Just started reviewing :)

**Comment by choliveira84** [comment]
Hi @AliciaGarciaGarcia , could you check the relevant status, please?

Thanks

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Resent in #529

**Pull request closed without merging**
