### PR TITLE
LPS-125436 Allow selecting a file by clicking the input so it works like JournalArticleSelector

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
As Document Selector is broken today on master, to test this PR, https://github.com/liferay-lima/liferay-portal/pull/1401 should be deployed first 🙂

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
