### PR TITLE
[TS] LPS-131594 Get the site's default locale, so the non-localized date of fragment is formatted according to the default locale instead of the American format.

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi Team,

**Issue description:** After the default language of the site is changed from en_US and a non-localized date is displayed in a fragment, the date format is always going to be the American format.

**Fix:** in _sanitizeDDMFormFieldValue after we retrieved the string from the empty locale we change the locale to the site default locale.

I sent this solution for validation, please find more information on the **PTR**: https://issues.liferay.com/browse/PTR-2445
**LPS** with repro steps: https://issues.liferay.com/browse/LPS-131594

Please review it. Thank you!

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
