### PR TITLE
LPS-125526 Set the default editing language to the defaultLanguage of the site

### PR DESCRIPTION
**Pull request by victorg1991**
Hey!

I've found a very simple solution to the bug LPS-125526 but I wanted to double check with you if it may have more implications. By default the language used as the editing language was the user language -- obtained with themeDisplay.getLanguageId -- but the application itself is using the default language of the site.

With this change I've made that the form is using also the default language of the site. I've checked in Web content structures, forms and app builder and everything is working fine. 

Here I'm sending the original solution and my fix applied to it just for you to see both posibilities, if you think the 2nd one is fine I can update the pr to leave only the needed changes :)

Thanks!

### CODE REVIEW

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hey @victorg1991

Thanks for your fix! Can you change the branch to have just your fix? I think it will be enough :) 
Thanks a lot!

**Comment by victorg1991** [comment]
Sure thing!

**Comment by victorg1991** [comment]
Hey @jeyvison This change was already done yesterday in other pr: https://github.com/liferay/liferay-portal/commit/b4f62cb505977f0e0227c83574245fbe37f56b81

**Comment by victorg1991** [comment]
So I'm closing this and marking the bug as no longer reproducible :)

**Pull request closed without merging**
