### PR TITLE
LPS-131631 Implement the validation interface for the string validation types

### PR DESCRIPTION
**Pull request by marcelabc**
Resending #415

Today, field validations are hard-coded in the frontend (see class), which doesn't allow developers to extend a validation and create another one.

This work is to provide an extension point in the backend. We are creating an extension in the backend (an interface), so the developer will be able to include new validations (implementing the created interface).

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Hey, @marcelabc. Apparently your pull is not exporting the package you created in the API module.

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
