### PR TITLE
LPS-132436 Migrate selection modal related to the `selectDDMStructure` event

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey @liferay-data-engine!

This is a part of [an ongoing epic](https://issues.liferay.com/browse/LPS-129246) to replace legacy AUI-based modals with Clay/React-based `openSelectionModal`. We have previously migrated DDM modals, in #407, but we were not aware of `openDDMPortlet` utilily. This PR is a first part of the task that migrates `openDDMPortlet` related to `structure`, similar to what is being done with `template` in #454.

I decided to have a granular approach with this task to make both working on it and reviewing easier. The other usages of `openDDMPortlet` in relation to `structure` are:
- [select_structure.jsp](https://github.com/kresimir-coko/liferay-portal/blob/LPS-132436/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/select_structure.jsp) 
- [edit_structure.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/edit_structure.jsp#L350-L381)

which I'll start working now. Let me know if you want me to couple that one to this PR or to send a separate PR for that other modal.

# 🧪 Testing
1. Content & Data > Dynamic Data Lists
2. Open the Add new List page
3. Click on `Select`

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
Hey @kresimir-coko 

Could you check the status of relevant test? Apparently, it's related to the select icon that you changed in DDL edit screen.
The message is: **Element is not present at "//a[contains(@class,'btn') and contains(@class,'taglib-icon')]/span[contains(.,'Select')]"**

Could you run locally one of these Dynamicdatalists tests that failed? just to make sure if my guess is correct.
Let me know if you need any help on this.

Thanks!

**Comment by kresimir-coko** [comment]
Hey @guilhermedcamacho I've never ran any CI tests locally, but my changes did, probably because of the `liferay-ui:icon` implementation change the DOM being rendered.

The DOM on `master` renders an `a` element that's styled to look like a button, but in this PR I'm removing the `url` attribute from  the `<liferay-ui:icon>` tag. I think that the removal of the `url` attribute is making it render as a `span` rather than an `a`element. So I'll fix it and push a new commit once I figure out the best way to do it! 

image

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:reevaluate:1217401_8098

**Comment by kresimir-coko** [comment]
ci:reevaluate:1217401_8098

**Comment by kresimir-coko** [comment]
Interesting... Gonna investigate.
`com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@class,'modal-body')]/iframe"`

**Comment by kresimir-coko** [comment]
Welp, got a classic `Unresolved requirement` error when I rebased and deployed so I'll leave this for tomorrow, but I think it's due to us migrating to `openSelectionModal`. So if you can check for me that would be okay, if not I'll tackle it tomorrow. Just let me know @guilhermedcamacho if we can update the CI test in case the DOM changes are valid.

**Comment by guilhermedcamacho** [comment]
Hey @kresimir-coko ,

If you still need to run Poshi tests locally, you just need to have the portal running and execute the command below in liferay-portal path:
Command: ant -f build-test.xml run-selenium-test -Dtest.class=TestClass#TestName
Example: ant -f build-test.xml run-selenium-test -Dtest.class=PGDynamicdatalists#ConfigureSpreadsheetListPG

Sure, we can discuss it together with our QA @emanuelfisilva to understand better if updating the Poshi test is the best solution.

Thanks again!

**Comment by kresimir-coko** [comment]
@guilhermedcamacho I've tested this on both `master` and this branch, and they behave the same (as previously established in the initial tests), but both variants have just one `modal-body` mention in the DOM once a modal is opened. So basically, I don't understand why CI is complaining there, in the [testray report](https://testray.liferay.com/reports/production/logs/2021-05/test-1-21/test-portal-acceptance-pullrequest(master)/8098/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.PGDynamicdatalists_ConfigureSpreadsheetListPG/index.html.gz) both before and after images are the same.

**Comment by guilhermedcamacho** [comment]
Hey @kresimir-coko ,

Would you mind talking with **John Co** (QA of frontend infra team) about this problem?
I talked with our QA @emanuelfisilva and he suggested this approach because he is very busy testing new features that we have implemented recently.

Let us know if you need any additional assistance from us.

Thanks for understanding.

**Comment by kresimir-coko** [comment]
Hey @john-co 👋 , I've been instructed to reach out to you regarding the failing CI in this PR.

If you take a look at the [testray report](https://testray.liferay.com/reports/production/logs/2021-05/test-1-21/test-portal-acceptance-pullrequest(master)/8098/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.PGDynamicdatalists_ConfigureSpreadsheetListPG/index.html.gz) you can see that both `Before` and `After` state of the modal is the same. But the CI is complaining about a missing `modal-body`.

This PR replaces the usage of `openDDMPortlet` with our modern `openSelectionModal`, so there might be some differences in DOM structure of the 2 modals. I've tested this manually, and looked at the DOM on `master` and on this branch, and they both have just one mention of `modal-body` once the modal is opened.

Do we have to update the CI test? Do I have to change something in my code? Please let me know ❤️

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
@nkkwon can you please analyze the failure, we may need a test fix.

**Comment by john-co** [comment]
I actually took a quick look and I think the test failure involves there being a 2nd iframe within an iframe in the PR. Likely can be fixed on poshi side to have the proper frame context.

https://user-images.githubusercontent.com/35235266/119867769-1d119300-bed3-11eb-9f5d-cbd2c47e01d1.mp4

This differs from the behavior at head where the Add List iframe is replaced by the Add Definition iframe:

https://user-images.githubusercontent.com/35235266/119867804-26026480-bed3-11eb-82a3-0b471101628e.mp4

**Comment by john-co** [comment]
@kresimir-coko, I found this [lexicon guideline](https://liferay.design/lexicon/core-components/modals/#modal-over-modal), to me it sounds like a design lexicon wants to avoid:

`Modal over modal is a not desired situation. Please, try to solve this situation in another way, like using a full page or driving the process to the correct place. In case this happens, make sure to provide a good experience preventing first modal closing by accidental interaction (as an example).`

Selection_071

cc/ @drakonux could you confirm what should be the expected behavior?

**Comment by kresimir-coko** [comment]
Oh I might have missed that difference @john-co, thank you very much I'll take a look and report back!

**Comment by kresimir-coko** [comment]
So, @john-co you opened the modal on the landing page while I was explicitly working inside the Dynamic Data Lists module, so I'll have to figure out this behaviour that you reported 🤔

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by john-co** [comment]
> I don't know all the context of this scenario. But yes, we/product designers should avoid showing a modal window over a modal window. Normally, this is a clue to know that the user flow is not good enough. Besides there are other alternatives instead of doing this modal over modal.

So for these scenarios:
1. modal A on top of a modal B, where modal B is completely hidden behind modal A
2. modal A inside modal B such as the screenshot above.
Both scenario 1 and 2 are bad UX?

**Comment by kresimir-coko** [comment]
I'll take a look at this a little bit more (both the CI error and the modal on top of modal behaviour) and write up my discoveries.

**Comment by kresimir-coko** [comment]
So the reasoning I needed the `z-index` prop and why the modals weren't of matching dimensions is because the `Add List`  modal was using an `openWindow` utility instead of `openModal`. I've tested my changes inside both the native module (Content & Data > DDL, and on the Landing Page where the extra modal opens up).

## 🔗  New Commits
- In https://github.com/liferay-data-engine/liferay-portal/pull/456/commits/03934bcba591f40739c03f55f611fdac1b0ae3ac I reverted the `zIndex` I added previously
- In https://github.com/liferay-data-engine/liferay-portal/pull/456/commits/bcc5479790aee05ad6012a627519a54b75a032de I migrated the usage of `openWindow` to `openModal`

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by kresimir-coko** [comment]
The way I read it the failure unique to this pull is saying that there is no `value` of the clicked Data Definition. I'm not sure what to do with it 🤷

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Comment by rodrigopaulino** [comment]
Hey, @john-co and @kresimir-coko. Since there's nobody from the Data Engine team working on this at the moment, would you mind closing this PR after the test finishes running, working on the fix on your repo and then sending the final solution to us (_if it needs review from the DE team_) when it's done?

Kind regards.

**Comment by john-co** [comment]
pushed to https://github.com/liferay-frontend/liferay-portal/pull/1142

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
