### PR TITLE
LPS-132017 Add Unit Tests

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-132017

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by mateussgn** [comment]
ci:close

**Comment by mateussgn** [comment]
ci:reopen

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
