### PR TITLE
LPS-127976 test fix

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-127976

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
resent https://github.com/liferay-data-engine/liferay-portal/pull/308

**Pull request closed without merging**
