### PR TITLE
LPS-124577 buildUpgradeTable

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @achaparro

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:app-builder

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
