### PR TITLE
LPS-125448 Check form field options if dataSourceType is empty

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hi! I've checked [this issue](https://issues.liferay.com/browse/LPS-125448) and seen that form fields are not being validated if it's dataSourceType is empty. I am not sure if this is expected or select field's dataSourceType should be set to "manual" by default.

Can you confirm if this is a valid solution?

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
@p2kmgcl LGTM :)

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
