### PR TITLE
LPS-123542 Repeated child HTML Field can only select Images from current site

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi!
Could you please review this pull request?
The referGroupId spoils the URL. The doAsGroupId is so old that I did not dare to revert, fearing it would cause regression.
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
