### PR TITLE
LPS-123853 Remove feature flag to show Searchable and Validation options in all fields of App Builder

### PR DESCRIPTION
**Pull request by mateussgn**

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
resent. See https://github.com/liferay-data-engine/liferay-portal/pull/65

**Pull request closed without merging**
