### PR TITLE
LPS-129447 We have to secure a place in newer versions for upgrade processes that are created for older versions

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-129447

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@carolmariaabb please see this.
This needed to come before your recently created upgrade process [here](https://issues.liferay.com/browse/LPS-125267). :)

Thanks.

**Comment by carolmariaabb** [comment]
> @carolmariaabb please see this.
> This needed to come before your recently created upgrade process [here](https://issues.liferay.com/browse/LPS-125267). :)
> 
> Thanks.

Thanks @rodrigopaulino!

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@rodrigopaulino merge conflict :/

**Comment by rodrigopaulino** [comment]
There you go, @jpince. Thanks for bringing that up.

**Comment by achaparro** [comment]
Hi @rodrigopaulino,

I have one question regarding this change, why this upgrade path is still needed?
`registry.register("3.10.0", "3.10.1", new DummyUpgradeStep());`

Thanks!

**Comment by rodrigopaulino** [comment]
> Hi @rodrigopaulino,
> 
> I have one question regarding this change, why this upgrade path is still needed?
> `registry.register("3.10.0", "3.10.1", new DummyUpgradeStep());`
> 
> Thanks!

Yes, @achaparro. For [this one](https://issues.liferay.com/browse/LPS-122906) that needs to be backported.

Thanks.

**Comment by achaparro** [comment]
Understood @rodrigopaulino,

Thanks!

**Comment by jeyvison** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @rodrigopaulino, could you rebase then rerun?

**Comment by jpince** [comment]
ci:reevaluate:1067401_8200

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
