### PR TITLE
LPS-130481 Space is missing between colon punctuation and text into Fieldset dialogs

### PR DESCRIPTION
**Pull request by EliveltonR18**
Changes for this issue: https://issues.liferay.com/browse/LPS-130481

### CODE REVIEW

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by EliveltonR18** [comment]
ci:test:sf

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by EliveltonR18** [comment]
ci:test:stable

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@marcelabc read my mind.

**Comment by EliveltonR18** [comment]
@rodrigopaulino hahaha true

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
