### PR TITLE
LPS-131834 Filter ddmFormFieldValues to be compatible with ddmForm

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-131834

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
@mateussgn the failures reported by CI are related to your pull. Could you please address them and push the required changes?

Thanks in advance.

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
resend: https://github.com/liferay-data-engine/liferay-portal/pull/471

**Pull request closed without merging**
