### PR TITLE
LPS-132795 baseline

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-132795

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
CI must not run without https://github.com/liferay-data-engine/liferay-portal/pull/533 changes, otherwise it will cause compile errors.

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
