### PR TITLE
LPS-123711 Not ignore the submit when a form is a Liferay.Form

### PR DESCRIPTION
**Pull request by boton**
Hey everyone, 

I rebase #63 but we have the same problems. 
I only want to delegate the submit to `data engine` when the `liferay-form` is valid. 

Some context liferay-app-builder#112 

Can anyone please review this?

### CODE REVIEW

**Comment by kevenleone** [comment]
Just started reviewing :)

**Comment by kevenleone** [comment]
@interaminense

**Comment by boton** [comment]
See #135.

**Pull request closed without merging**
