### PR TITLE
[TS] LPS-123887 creating a recursive call for updateLocalizationMap for updateDDMFormInputValue to avoid regression

### PR DESCRIPTION
**Pull request by bakayattila**
HI @liferay-data-engine Team,

Could you review this issue?
https://issues.liferay.com/browse/LPS-123887

Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
