### PR TITLE
LPS-123072 Editor configuration should be unique to each field

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket: https://issues.liferay.com/browse/LPS-123072

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
resent. See https://github.com/liferay-data-engine/liferay-portal/pull/58

**Pull request closed without merging**
