### PR TITLE
LPS-123614 set current value when editor is on source mode

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-123614

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
