### PR TITLE
LPS-130035 Code correction after executing the gw formatSource 

### PR DESCRIPTION
**Pull request by choliveira84**
https://issues.liferay.com/browse/LPS-130035

### CODE REVIEW

**Comment by choliveira84** [comment]
ci:test:sf

**Comment by choliveira84** [comment]
ci:test:relevant

**Comment by choliveira84** [comment]
ci:test:sf

**Comment by choliveira84** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Resent: https://github.com/liferay-data-engine/liferay-portal/pull/405

**Pull request closed without merging**
