### PR TITLE
LPS-126713 Pass the resource primary key to the JournalItemSelectorCriterion so that the already upload images are loaded

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @marcelabc, @jeyvison,

Taking a look at the ImageDDMFormField, it seems to be available for web content, document library and forms, it is because the is forms. I don't know if it is intended or not, but at this moment we are facing a problem since we are going to show the web content images tab in document library and forms and it doesn't make sense.

Please see the following screenshot, it is when you click select in image field on document library or forms.

New_Contract_-_Liferay

On 7.3, we allow the image field only in web content, so, IMHO, we should move the image field to journal ddm form field module and change the scope to show it only in web content.

Available fields for document library in 7.3

New_Document_Type_-_Liferay

cc: @victorg1991

**Comment by jeyvison** [comment]
@ealonso Got it. Let me check it @luiz-jardim if this field makes sense in Forms. If it doesn't we can just scope it for Data Engine

**Comment by victorg1991** [comment]
Hey @jeyvison any news about this? We can help doing th needed changes once you decided what should be done :)

**Comment by jeyvison** [comment]
Hey @victorg1991 :)  @luiz-jardim talked with me yesterday about and he still thinks that the field should exist on Forms/DL.  I'm gonna investigate how we can hide/show the new tab depending on where the field is used. If you have any idea about it, please let me know :)

**Comment by ealonso** [comment]
Hey @jeyvison,

One possible solution could be created a new interface ImageDDMFormFieldCriterionContributor, and a OSGI Tracker, so then we can implement it for Journal.

I can take care of it if you want and send the solution to your.

What do you think?

**Comment by ealonso** [comment]
@jeyvison another solution is copy/paste this field in journal and make it available only for journal.

**Comment by jeyvison** [comment]
> Hey @jeyvison,
> 
> One possible solution could be created a new interface ImageDDMFormFieldCriterionContributor, and a OSGI Tracker, so then we can implement it for Journal.
> 
> I can take care of it if you want and send the solution to your.
> 
> What do you think?

@ealonso Got it. I think that is better than the second solution since there is no specific scope for web content rigth now. If you can send it that would be awesome :)

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
