### PR TITLE
LPS-129892 Fix TextHTMLField syncReadOnlyUI method

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi !
Based on Marcela [comment](https://github.com/liferay-data-engine/liferay-portal-ee/pull/17#issuecomment-820714810) I made the changes to master.
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
fwd : https://github.com/liferay-data-engine/liferay-portal/pull/401

**Pull request closed without merging**
