### PR TITLE
[DE-Migration] LPS-126471 normalize option value for all available languages

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-126471

### CODE REVIEW

**Comment by oliveiraaraujo** [comment]
LGTM!

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1112004_8302

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
