### PR TITLE
LPS-121695 Use scopeGroupId just like in DDMTemplateStagedModelDataHandler

### PR DESCRIPTION
**Pull request by vendeltoreki**
Dear @liferay-data-engine team,

Can you please review whether this change in DDM Structure import would break any use-case?

For details, see [LPS-121695](https://issues.liferay.com/browse/LPS-121695?focusedCommentId=2288956&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2288956).

cc: @crodriguezy

Thanks,
Vendel

### CODE REVIEW

**Comment by jeyvison** [comment]
Hey @marcelabc , can you please review this one? thx!

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
