### PR TITLE
LPS-130075 Create display renderers for DDL

### PR DESCRIPTION
**Pull request by stsquared99**
/cc @ctang3 @Preston-Crary

Could you please take a look specifically at a6308fb?
The read only render shouldn't display an actual input field.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hi @marcelabc @rodrigopaulino,
can either of you take a look at this sometime this week? If you need more information about it let us know, thanks!

**Comment by rodrigopaulino** [comment]
Sure thing, @Preston-Crary.

We've been facing heavy load from other fronts, but we are prioritising this pull request for this week's reviews.

Thanks for understanding.

**Comment by Preston-Crary** [comment]
@stsquared99 I just noticed the commits are all using the wrong ticket, it should be LPS-130075. Please reword the ticket and force push with the change, thanks!

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
