### PR TITLE
LPS-129256 This is recursive. No need for getting the nested fields at the same level

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-129256

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by tayannasotero** [comment]
ci:forward

**Pull request closed without merging**
