### PR TITLE
LPS-129826 check if field belongs to a fieldset before allowing dragging

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-129826

### CODE REVIEW

**Comment by jpince** [comment]
@marcosapmf please manually forward to Brian. Not retesting because load is high right now.

**Comment by ealonso** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]
LGTM

**Review by mateussgn — COMMENTED** [review]
ci:forward

**Comment by mateussgn** [comment]
ci:forward

**Pull request closed without merging**
