### PR TITLE
LPS-129130 Fix the condition to avoid null pointer

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Comment by rodrigopaulino** [comment]
ci:test:echo

**Comment by rodrigopaulino** [comment]
LGTM. Just running the Echo suite to verify that this doesn't break any other tests, but, locally, the reported error looks fixed now. :)

**Review by rodrigopaulino — APPROVED** [review]

**Comment by Tim-Cao** [comment]
Hi @rodrigopaulino, all failure cases from ci:test:echo are functional tests and common ones.

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
