### PR TITLE
LPS-131834 Get values only for ddmFormValues

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-131834

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Review by rodrigopaulino — COMMENTED** [review]
@mateussgn, is that a specific reason why you chose to make these adjustments on the local service side? It seems to me that the problem occurs after that call to the local service, on the DDMFormValuesToFieldsConverter side.

**Comment by rodrigopaulino** [comment]
The failures are not related to this pull request (it appears that app-builder-workflow-web wasn't completely removed from master). The batch test `js-unit-jdk8` runs all modules' Javascript unit tests and it's present in our relevant suite.

**Comment by mateussgn** [comment]
@rodrigopaulino, you are right, but the problem occurs due to the wrong return from the local service, which is returning not needed data.

**Comment by rodrigopaulino** [comment]
As per discussion, we decided to go with the more surgical solution that impacts the least amount of modules possible.

**Comment by mateussgn** [comment]
Resent: https://github.com/liferay-data-engine/liferay-portal/pull/464

**Pull request closed without merging**
