### PR TITLE
LPS-128562 no needed since we create a nested dynamic element map during the recursion

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-128562

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:help

**Comment by marcosapmf** [comment]
ci:test:echo

**Comment by rodrigopaulino** [comment]
LGTM

**Review by rodrigopaulino — APPROVED** [review]

**Comment by ealonso** [comment]
Hey @rodrigopaulino @marcosapmf,

Since this one is changing some code in echo components, Could you please send this one to @liferay-echo user? so, we can review it.

Thanks!
Eudaldo

**Comment by marcosapmf** [comment]
> Hey @rodrigopaulino @marcosapmf,
> 
> Since this one is changing some code in echo components, Could you please send this one to @liferay-echo user? so, we can review it.
> 
> Thanks!
> Eudaldo

Hey @ealonso ,
forwarded https://github.com/liferay-echo/liferay-portal/pull/3929

As we talked on slack, I'll keep this pull opened and forward it after you guys review the pull above and if every is fine. This way, we can save time of running the ci tests again, since the relevant suite already passed here.

Thank you very much for your help

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
