### PR TITLE
LPS-129755 pass editingLanguageId through useSyncValue so the useEffect that cleans the value reference can be trigged

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-129755

### CODE REVIEW

**Comment by marcelabc** [comment]
LGTM 🎉

**Comment by jpince** [comment]
@marcosapmf @marcelabc thank you!! If the tests finish after your day is over, can this PR be forwarded to Brian?

**Comment by marcelabc** [comment]
@jpince yes!

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
