### PR TITLE
LPS-130720

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-130720

Should be forwarded to Bchan as per: https://github.com/brianchandotcom/liferay-portal/pull/101094#issuecomment-826827101

### CODE REVIEW

**Comment by brianikim** [comment]
SF Failure does not look related.

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hi @brianikim, how are you doing?
Could you investigate why this is happening? Try to run the SF locally or do a rebase, I don't know if you have any ideas..
Let me know if you have any success to fix this issue, please!

**Comment by brianikim** [comment]
Hello @marcelabc ,

You can also test on your local branch, but this SF fails for translation-web regardless of whether my commit is included or not.

**Comment by brianikim** [comment]
Pushed a new branch to test the SF. New Pr here: https://github.com/liferay-data-engine/liferay-portal/pull/406

**Comment by guilhermedcamacho** [comment]
Pushed a new branch to test the SF. New Pr here: #408

**Pull request closed without merging**
