### PR TITLE
LPS-134885 Add new DDMTemplate search method

### PR DESCRIPTION
**Pull request by lfbesada**
Hi Team,
To implement https://issues.liferay.com/browse/LPS-124478 we need DDMTemplate search methods that accept multiple resourceClassNameIds. We have developed these new methods, please, could you review this PR?
Thanks a lot!
Regards

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Wrong LPS number, we are going to change it and resend.
Thanks!!

**Pull request closed without merging**
