### PR TITLE
LPS-129541 Only submit a liferayForm if doesn't have any errors : recreate 0d3d4d6da8f3e10dafbf20d9ff95215b65c783a6 removed on move file

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
@boton I recreate the same changes (lost on the migration) from the commit 0d3d4d6da8f3e10dafbf20d9ff95215b65c783a6.
Can you check it ?

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Tested and working for me 😄 
Thank you so much @AliciaGarciaGarcia for rescuing the lost code.

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by rodrigopaulino — APPROVED** [review]
This was already [reviewed before](https://github.com/liferay-data-engine/liferay-portal/pull/135#issuecomment-759812681) and it's working as expected. LGTM.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
