### PR TITLE
LPS-127461 we should not pass fieldName when adding  fieldset by double clicking

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-127461

### CODE REVIEW

**Review by interaminense — APPROVED** [review]
LGTM

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]

**Review by jeyvison — APPROVED** [review]
LGTM

**Comment by jeyvison** [comment]
ci:forward

**Comment by kevenleone** [comment]
Just started reviewing :)

**Pull request closed without merging**
