### PR TITLE
LPS-127978 make sure the value is a number before rounding it

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-127978

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Hey, @marcosapmf. This fix breaks the Numeric field frontend unit test. Could you please check to see if your fix needs correction or the test needs adaptation?
Let me know if you need any help. :)

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
