### PR TITLE
LPS-130068 since dataSourceType field is not visible anymore, we need to update options rule so we guarantee they are visible even if dataSourceType is not

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-130068

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by rodrigopaulino — CHANGES_REQUESTED** [review]
Hey, @marcosapmf. The unit and integration tests failures seem related to these changes. Could you check that?

Thanks in advance.

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-data-engine/liferay-portal/pull/383

**Pull request closed without merging**
