### PR TITLE
LPS-128325 Do it only for web content structures

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hey @ealonso  :) Can you please check the failling tests? Thanks!.

**Comment by ealonso** [comment]
Hey @jeyvison,
I'll take a look on Thursday since I'm OOO.
Regards,
Eudaldo.

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
resent https://github.com/liferay-data-engine/liferay-portal/pull/292

**Pull request closed without merging**
