### PR TITLE
LPS-129346 Prevents moving a FieldGroup into itself and into another FieldGroup

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Hey Data Engine Team 👋,

This change brings some improvements and covers some more cases of this problem, this seems to have been partially corrected at https://issues.liferay.com/browse/LPS-128117 but will correct for Forms after Forms stopped using LayoutProvider.

The LayoutProvider implementation did not deal well with preventing a FieldGroup from moving inside into itself, because it did not give Feedback to the user that this is not possible and was an expensive operation when trying to search for the target within the source with the visitor and also it is not the appropriate place to be added, it is the responsibility of the DnD mechanism.

There were also other untreated behaviors, such as:

- Drop the common Field inside itself
- Drop a FieldGroup inside any Field (This means that the FieldGroup can be added in a placeholder.)

These behaviors were not perceived because there was a `try catch` that captured the handlers' errors and suppressed what is invisible to the user if it worked or was wrong and it was also an insecure and sensitive way to deal with these use cases.

---

Move a FieldGroup into itself, In conventional mode, we would be visiting all the fields within it to check if the target belongs to the Field root (in this case the source), but this can be very slow depending on the depth and it is very expensive in this hot path instead this method implement heuristic algorithm based on two assumptions:

- The target indexes are the same as the source indexes
- The target depth is greater than the source

The indexes are an `Array<Object>` that contains the index of the Field according to the depth level, the head of the array is the current loc and the tail is the root of the tree. It does not compare all target indexes just up to the same level of depth as the source.

```js
[
  {pageIndex: 0, rowIndex: 1, columnIndex: 0}, // <- Head (deeper)
  {pageIndex: 0, rowIndex: 0, columnIndex: 0},
  {pageIndex: 0, rowIndex: 0, columnIndex: 0}, // <- Tail (root)
]
```

The comparison of the indexes also fails in the first index that is not equal to the source index to fail early.

---

The last commit is not related to these problems mentioned above, but only an improvement in the declaration of variables that were degrading the readability.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Review by rodrigopaulino — COMMENTED** [review]
Hey, @matuzalemsteles. Is [this order](https://github.com/liferay-data-engine/liferay-portal/pull/340/commits/fa7e86d539f62705d55d3efeb63935e4f6c7df90#diff-764e700d6c5b42e4fdb5d9f9397313eceafcd934b68c477d2a745e79c0ce6e49R27-R92) necessary or can we sort those constants?

**Comment by matuzalemsteles** [comment]
Hey @rodrigopaulino, Yeah, we normally use the declaration order for these cases.

**Comment by rodrigopaulino** [comment]
Got it, @matuzalemsteles. Thanks for clarifying. LGTM.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:forward

**Pull request closed without merging**
