### PR TITLE
LPS-128182 Display current lang values if lang undefined

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Hi @adolfopa ,
looks like your solution is similar to the one at https://github.com/liferay-data-engine/liferay-portal/pull/278
could you please take a look at that and check if that works to you?

Thanks in advance :)

**Comment by adolfopa** [comment]
@marcosapmf Both solutions are complementary. WCM needs to inject a custom language ID, but by default, values should be rendered using the current selected language.

See https://github.com/liferay-data-engine/liferay-portal/pull/285

Thanks!

**Pull request closed without merging**
