### PR TITLE
LPS-127705 Don't execute any action if we are dropping a field inside the same parent

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
Hey @sandrodw3,
Unfortunately, I tried to replicate the bug with your changes and could not reproduce the expected result. I don't know if a code, that got merged, did something with your solution...
Please, see the video:

https://user-images.githubusercontent.com/15846206/107968418-1a76d780-6f8d-11eb-9d6b-0ff8a4acf4c7.mp4

**Comment by sandrodw3** [comment]
Hey @mateussgn! 🙂 thanks for let me know. I had some not-pushed changes, I'm sorry. I have updated the PR, could you give it another try? 😄

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:stable

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
Hey @sandrodw3 I've tried again, but this time is still showing "**Error**: Cannot read property 'settingsContext' of undefined". 😔

**Comment by sandrodw3** [comment]
Thanks @mateussgn, I'll take another look and I'll update the PR again!

**Comment by sandrodw3** [comment]
Hey @mateussgn, I already pushed another commit 🙂 I have tested most cases and I think it's working well right now. I'm not launching the CI because it seems we have to wait until the vulnerability problem they announced this morning is solved. But could you give it another try locally? Thanks!

**Comment by mateussgn** [comment]
Hey @sandrodw3 , this time it worked really well 😀. Thanks for the patience. I'll run the CI in order to get this issue done.

**Comment by mateussgn** [comment]
ci:test:relevant

**Review by mateussgn — APPROVED** [review]

**Comment by sandrodw3** [comment]
@mateussgn same to you! 🙂  thanks a lot for your feedback!

**Comment by sandrodw3** [comment]
Hi @jeyvison! It seems you have to approve the changes for the PR to be forwarded 🙂 could you do it? Thanks!

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
