### PR TITLE
LPS-129865 Restore the defaultLanguageId from the fieldset to its fields

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related issue: https://issues.liferay.com/browse/LPS-129865

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
LGTM

**Comment by brianchandotcom** [comment]
@rodrigopaulino @ealonso @jeyvison I merged this manually.

**Comment by rodrigopaulino** [comment]
Closing as per https://github.com/liferay-data-engine/liferay-portal/pull/365#issuecomment-810163619

**Pull request closed without merging**
