### PR TITLE
LPS-122104 - Non localizable DDM boolean fields editable in all lang

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Non-localizable DDM boolean fields editable in all the languages when child of a separator field

https://issues.liferay.com/browse/LPS-122104

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
@jeyvison I tested manually many scenarios with the boolean type field with localizable property enable/disable, all scenarios work! LGTM :)

**Comment by jeyvison** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
