### PR TITLE
LPS-125969 Observe form builder height and update the scroll after changing the language

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
cc: @natocesarrego

**Comment by jeyvison** [comment]
Hi @victorg1991 :)

I pulled your PR and executed an ant all on it, just in case. The behavior does not seem consistent. maybe I'm doing something wrong?

I'm uploading a video so you can see whats happening. Let me know what you think :)


[Gravação de Tela 2021-01-21 às 14.13.10.zip](https://github.com/liferay-data-engine/liferay-portal/files/5850937/Gravacao.de.Tela.2021-01-21.as.14.13.10.zip)

**Comment by victorg1991** [comment]
Hey @jeyvison 

I get pretty consistent result, but given that you are experienced that I do agree that this is not a valid solution. It seems that the problem is not addressable from outside the FormRenderer. 

 I think we should tweak the react app a bit to avoid some renders. For now, I'm not familiar enough with the form render app and the issue is not critical I'll leave it open for now

**Pull request closed without merging**
