### PR TITLE
LPS-124636 Check if value is not null since for some cases, like separator, we don't have value.

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:forward

**Comment by mateussgn** [comment]
@jeyvison this PR fixes the [LPS-124012](https://issues.liferay.com/browse/LPS-124012) too. Thanks for warning me about it.

**Comment by jeyvison** [comment]
Great, @mateussgn! Can you please link the ticket with the one of this PR and close it?

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
