### PR TITLE
LPS-130720

### PR DESCRIPTION
**Pull request by brianikim**
Resending: https://github.com/liferay-data-engine/liferay-portal/pull/402

### CODE REVIEW

**Comment by brianikim** [comment]
The SF Failure is not related to this PR. It fails regardless of my commit included or not.

**Comment by brianikim** [comment]
@marcelabc

**Comment by brianikim** [comment]
Hello @liferay-data-engine ,

Please let me know how you guys would like to proceed. Again, the SF failure was reproducible regardless of my commit in the branch (Let me know if your testing differs).

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Hello @brianikim ,

I pushed a [new branch](https://github.com/liferay-data-engine/liferay-portal/pull/408) to test the SF and it works. I'm waiting the relevant test to forward this PR to Bchan. 
Thank you!

**Pull request closed without merging**
