### PR TITLE
LPS-122340 Create a way to reference DDM field attributes from the database

### PR DESCRIPTION
**Pull request by Preston-Crary**
@natocesarrego @jeyvison tried to make this as backwards compatible as possible.  This opens the door for preventing pages from being removed if they're referenced by a form, see the test for an example in 7e61dddf4718fe409cefac285420645783035d96. Same logic can be applied to web content articles or documents used by DDM.  I'm not sure what the business logic for that should be, so I'm leaving that part out.

I've tested the upgrade with custom document types, DDL, forms and web content.

If you are fine with these changes please forward to @shuyangzhou and we'll check it for performance.

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hi @Preston-Crary . Thanks a lot for the PR, man. Can you please take a look at the test failures? The first one is probably unrelated but the others i believe were affected by the changes

**Comment by Preston-Crary** [comment]
@jeyvison sorry, should have run tests beforehand.  I'll work through the test failures and resend.

**Comment by Preston-Crary** [comment]
Please see https://github.com/liferay-data-engine/liferay-portal/pull/36

**Pull request closed without merging**
