### PR TITLE
LPS-125829 Use the reference value for the input value

### PR DESCRIPTION
**Pull request by victorg1991**
Hey!

I've updated both checkbox multiple and Radio fields to reflect the correct reference value. I am going to open another bug for the Option fields, as I've found more problems with it and I want to take more time reviewing it. In the meantime I think we can merge this :)

Thanks!

### CODE REVIEW

**Comment by victorg1991** [comment]
This is the bug I've created for the select field: https://issues.liferay.com/browse/LPS-126156

**Comment by victorg1991** [comment]
checking

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
I've fixed the js test, not sure if the poshi test are flaky or not. I'm giving it another try just in case

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
I'm checking the poshi tests

**Comment by victorg1991** [comment]
It seems that my changes are affecting other applications so I'm going to try another approach doing it in Journal side

**Pull request closed without merging**
