### PR TITLE
LPS-127960 buildTaglib

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-127960

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Comment by rodrigopaulino** [comment]
Hey, @marcosapmf.

Your changes look good to me, but, during my local testing, I still noticed some reported behaviors:
1. The Image field never loads the default language value when a new translation is added;
2. The step 21 of the ticket still occurs for the Rich Text and Single Selection fields.

Please let me know if those are intended somehow or if you need assistance with this. But, since this hasn't passed the steps, I'll close this PR and request additional work on the LPS.

Thanks a lot for your contributions. :D

**Comment by marcosapmf** [comment]
@rodrigopaulino, I tested this issue over https://github.com/liferay-data-engine/liferay-portal/pull/236 pull and it works. I think we can forward this and test when that othet pull gets merged. What do you think?

**Comment by rodrigopaulino** [comment]
As we talked privately, @marcosapmf, I'll close this and send a new one with a wordsmith change. Thanks a lot for your work, Marcão!

**Comment by rodrigopaulino** [comment]
sent https://github.com/liferay-data-engine/liferay-portal/pull/245

**Pull request closed without merging**
