### PR TITLE
LPS-132122 Add onPaste property and Remove rounding for decimal numbers

### PR DESCRIPTION
**Pull request by danvb112**
Related issue: https://issues.liferay.com/browse/LPS-132122

### CODE REVIEW

**Comment by danvb112** [comment]
ci:stop

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Related issue: https://issues.liferay.com/browse/LPS-132122

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Hey @danvb112 ,

SF has failed. Could you run formatSource and commit changes?

Thanks!

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by marcelabc — CHANGES_REQUESTED** [review]
Hi @danvb112 ,
The CI failure is related to this work. Could you fix and resend please? Thank you :)

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by choliveira84** [comment]
@danvb112 , as we talked on early daily, this PR will be closed. Please, send another PR with your solution.

Thanks.

**Pull request closed without merging**
