### PR TITLE
LPS-125369 move the logic of getting the title translated value to back-end

### PR DESCRIPTION
**Pull request by marcosapmf**
This is a follow up for https://issues.liferay.com/browse/LPS-125369
I'm moving the logic of getting the translated values for the article title to backend due to https://issues.liferay.com/browse/LRQA-64147. This issue only occurs when Poshi test is running and we are not able to reproduce it manually. Somehow, the localzed-input value is not updated at the moment that _saveArticle is running. So the solution I found was just send the translated languages to backend and filter the values there

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
@marcosapmf LGTM!

**Comment by jeyvison** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @marcosapmf @jeyvison,

Could you please send to us the pr that modify our components? So, we can check if everything is ok in journal portlet in this case,

@victorg1991 was working on a similar issue and he has another solution for it, also this pull has conflicts with master.

Regards,
Eudaldo.

**Comment by victorg1991** [comment]
I've sent a pr yesterday chaning almost the same lines fixing https://issues.liferay.com/browse/LPS-125394

**Comment by victorg1991** [comment]
Checking the issue again, this should be solved with my changes, can you check it out?

**Comment by jeyvison** [comment]
> Hey @marcosapmf @jeyvison,
> 
> Could you please send to us the pr that modify our components? So, we can check if everything is ok in journal portlet in this case,

 Sure 👍 
> 
> @victorg1991 was working on a similar issue and he has another solution for it, also this pull has conflicts with master.
> 
> Regards,
> Eudaldo.

**Comment by jeyvison** [comment]
> Checking the issue again, this should be solved with my changes, can you check it out?

I'll take a look. Thanks, @victorg1991 =D

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
