### PR TITLE
LPS-132115 Import libs and include document library scope

### PR DESCRIPTION
**Pull request by choliveira84**
https://issues.liferay.com/browse/LPS-132115

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
SF has failed.

**Comment by choliveira84** [comment]
ci:test:sf

**Comment by choliveira84** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @ealonso and @adolfopa

Just to let you know that we're adding a new parameter to the DE Builder Taglig. It won't add new feature/behavior, we just want to use this parameter to scope the fields available in the sidebar 👍 

Let us know if you have any questions or concerns! Thank you :)

**Comment by guilhermedcamacho** [comment]
Hey @choliveira84 , it seems that Poshy testes are failing because the field "Link to Page" is not visible.
The message is: **Element is not present at "//div[contains(@class,'field-type')]//span[normalize-space(text())='Link to Page']"**

Could you run locally one of these six tests that failed? just to make sure if my guess is correct.
Let me know if you need any help on this.

**Comment by choliveira84** [comment]
> Hey @choliveira84 , it seems that Poshy tests are failing because the field "Link to Page" is not visible.
> The message is: **Element is not present at "//div[contains(@Class,'field-type')]//span[normalize-space(text())='Link to Page']"**
> 
> Could you run locally one of these six tests that failed? just to make sure if my guess is correct.
> Let me know if you need any help on this.

@guilhermedcamacho I Will fix and push again. Thanks

**Comment by choliveira84** [comment]
ci:test:sf

**Comment by choliveira84** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
