### PR TITLE
LPS-127657 Update editor config with desired language and direction when switching language

### PR DESCRIPTION
**Pull request by sandrodw3**
First part of this PR has already been reviewed by @liferay-frontend in https://github.com/liferay-frontend/liferay-portal/pull/850 (cc @julien @wincent)
So the only commit that requires review here is https://github.com/liferay-data-engine/liferay-portal/pull/289/commits/a41d178736db6d8983935c27a334d5d90e583dcb
Thanks! 😄

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@marcelabc, @sandrodw3, test failures seem related since they also showed up in https://github.com/liferay-frontend/liferay-portal/pull/850

I'd say we should take a look and see if we can figure out what's going on there!

**Comment by sandrodw3** [comment]
> @marcelabc, @sandrodw3, test failures seem related since they also showed up in [liferay-frontend#850](https://github.com/liferay-frontend/liferay-portal/pull/850)
> 
> I'd say we should take a look and see if we can figure out what's going on there!

Thanks @jbalsas 🙂  I'll take a look!

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Review by marcosapmf — APPROVED** [review]

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
@sandrodw3 tested and working on MB 😄

**Comment by tayannasotero** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
