### PR TITLE
LPS-132279

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Resending #459

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@guilhermedcamacho please sort the accep-if-input key and run buildLang again. Discard the old commit.

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-data-engine/liferay-portal/pull/468

**Pull request closed without merging**
