### PR TITLE
LPS-132437 Migrate dynamic data template selection modals

### PR DESCRIPTION
**Pull request by markocikos**
@guilhermedcamacho @rodrigopaulino 

This is a followup on https://github.com/liferay-data-engine/liferay-portal/pull/466

I rebased commits, no changes in code.

The semver failure in https://github.com/liferay-data-engine/liferay-portal/pull/466#issuecomment-849143015 seems unrelated, we are not modifying `com.liferay.portlet.expando.model.impl` package in this PR. Just in case, I ran `gradle baseline` on three modules we do update. I also ran it on `portal-impl` and `portal-kernel`. None of these updated any semver.

The second failure also seems unrelated, looks like some internal CI failure.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
@markocikos as I could see, I'm not sure what was causing the semver error before, but I can tell that the `com.liferay.portlet.expando.model.impl` is currently on version 1.4.0 (which means it was not updated as indicated by the test results) and if you ran baseline against `portal-impl` and nothing changed to you, the breaking change appears to have been removed since yesterday.

Thanks for sending the pull again.

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Created a new PR #479

**Pull request closed without merging**
