### PR TITLE
LPS-125039 Add missing classes to allowed XStream types list

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by cvanut** [comment]
Hey @pavel-savinov , @jeyvison asked me to take a look in Forms failures in this PR. 
I verified in [Forms test suite](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1387945901), and according to the analysis, all the following tests are also failing in our suite, with the same error presented in your PR. 

FormRules#DeleteFieldThatBelongsToARule
FormRules#ViewPredefinedValueCanBeUsedToRequireAnotherField
FormRules#ViewExistingFormRuleIsNotCopiedToNewForm
FormRules#UseIsNotEmptyRuleToShowField
FormsJumpToPage#ViewRuleAfterOptionValueEdit

Then, these failures are not related to your changes. I'll add these tests to quarantine, until we verify if it's a bug or a testfix, since I am still analyzing the failure.

**Comment by jeyvison** [comment]
ci:forward

**Comment by jeyvison** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
