### PR TITLE
LPS-133183 This may be a blank string instead of null or undefined

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @liferay-data-engine ,
Could you please review this pull request?

Steps to reproduce:

1. Start a vanilla master.
2. Create a web content structure with minimum 2 text fields and add a translation to it in any language (I used Hungarian, but also tested with Dutch before).
3. Start editing a new web content with the above created structure.
4. Fill out one of the fields.
5. Change the language to Hungarian and fill out the other field.
6. Publish the web content.
7. Open the published web content for editing and review the Hungarian translation.

Original pull: https://github.com/liferay/liferay-portal-ee/pull/23205
This issue was presented on the older branches but It turned out that fix was also needed for a master. 
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Hey @MarcellGyopos ,

I could not reproduce these steps related to ticket [LPS-128686](https://issues.liferay.com/browse/LPS-128686) on Master, everything is working fine without your code. Could you attach a video in Jira ticket reproducing this issue? Maybe I did't understand well some step.

In addition I also tried to reproduce the steps in the ticket [LPS-133183](https://issues.liferay.com/browse/LPS-133183) referenced in the title of this PR, but your code didn't solve the issue explained there.

Let me know if you need any help.

I would like to suggest you avoid starting a new **ci:test:relevant** if already have one invoked or running for the PR, as we should conserve CI resources of the company. This repository start tests automatically when the PR in opened.

Thanks for understanding.

**Comment by guilhermedcamacho** [comment]
Hey @MarcellGyopos ,

As you told me in Slack, the steps to reproduce the error is slight different of mentioned in ticket [LPS-133183](https://issues.liferay.com/browse/LPS-133183) , so I will put them here to be clear to someone else.

The steps are:

1. Start the master.
2. Go to ddm list and make a structure with a text field. 1 is enough.
3. Make a list and try to add an instance.
4. Don’t fill the default language, switch to something else at the start then fill it, then switch back to the default language, then switch back again to lang you filled.
If the text disappeared you were reproduced the issue.

I would suggest you to create a new ticket for this bug, so the QAs will be able to track and test this issue following these steps.

Thanks for contributing :smile:

cc: @emanuelfisilva

**Review by guilhermedcamacho — APPROVED** [review]

**Pull request closed without merging**
