### PR TITLE
[DE-Migration] LPS-127602 Update editor configurations with the new generated instanceId

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-127602

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @rodrigopaulino,

Would you mind explaining the reasoning behind this change?

I am afraid with this you are hiding the real problem that I described in https://github.com/liferay-data-engine/liferay-portal/commit/556f1298718b1af71ce1aca5030f46cb334cc66c.

The field names are not properly parsed and they end up being generated with loads of `undefined`s in the name. I fear this will cause other issues in the future.

Thanks!

**Comment by rodrigopaulino** [comment]
Sure thing, @4lejandrito.

The field you were investigating, where you could see the weird name with lots of undefined values, is just a dummy field used for visualization purposes. For future reference, the body of the structure, where all fields are disabled, is just there to reflect the changes made in the settings sidebar, which contains the relevant information about the field that will be persisted after all. So there's no bug there. :)

Hope this clarifies.

**Comment by mateussgn** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Cool. Thanks @rodrigopaulino!

**Pull request closed without merging**
