### PR TITLE
LPS-133831 The Number and Boolean fileds value changes after upgrade

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related issue: https://issues.liferay.com/browse/LPS-133831
Resending #518

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
LGTM :tada:

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
