### PR TITLE
LPS-128927 add a tooltip to the content row 

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
Hi @boton !
Could you please confirm that this PR fixes the behavior described in [LPS-128927](https://issues.liferay.com/browse/LPS-128927) ?
It is because I've tried to reproduce, and it's still the same behavior shown in the ticket video :/ 
thanks in advance!

**Comment by boton** [comment]
Hi, @marcelabc it's my fault I remove the tooltip provider because we have a general provider added here https://github.com/liferay-frontend/liferay-portal/pull/855#issue-583324217.
I tested the Friday and works for me but now doesn´t work. I´m going to drop mi last commit.

This is how it looks now:

image

It´s weird because we need two nested TooltipProviders to get in work.

image
image

/cc @AliciaGarciaGarcia

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Comment by rodrigopaulino** [comment]
Rebase https://github.com/liferay-data-engine/liferay-portal/pull/326

**Pull request closed without merging**
