### PR TITLE
LPS-126017 Set appropriate input direction corresponding to the current editing language id

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @pavel-savinov, those are real failures, Could you please take a look at it?

**Comment by pavel-savinov** [comment]
@ealonso @jeyvison Resent [here](https://github.com/liferay-data-engine/liferay-portal/pull/172) with adapted tests. Thanks!

**Pull request closed without merging**
