### PR TITLE
LPS-126672 Choose the default value if there is no for the editing language

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hi @marcelabc . Instead of passing `defaultLanguageId` as parameter for each calling method can we put it in the AppContext or DataLayoutBuiderContext and get it from context so we can avoid [Prop drilling](https://kentcdodds.com/blog/prop-drilling)?

**Comment by marcelabc** [comment]
Hi @jeyvison !
AppContext already has the default/editingLanguageId properties. The problem is that there are cases the field has a different language than the context (fieldset created with defaultLangId 1 and has been added to a structure that has a different language)

**Pull request closed without merging**
