### PR TITLE
[DE - Migration] LPS-125650 Update DDM field types

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @nhpatt @adolfopa

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
hi @ealonso :)

It looks like this one generated a few unique failures. Also, do you think it's really worth to create 3 new modules just to hold the new constants? Can we just use the already existent API modules?

**Comment by ealonso** [comment]
Hey @jeyvison,

Thanks for taking a look at it, I'm trying to fix the tests.

Regarding to the modules, IMHO having separate modules make easier to understand what is the purpose of those modules. For example, if we just need to use journal type, then we need to add a dependency to all dynamic-data-mapping-api, just for only one class.

Also, this module has the old implementation and the new one, which is confusing if you not are a member of DDM team, in my personal case it is really difficult to know which are the new implementation classes.

Please let me know what do you think about it.

Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
> Hey @jeyvison,
> 
> Thanks for taking a look at it, I'm trying to fix the tests.

Thanks!

> 
> Regarding to the modules, IMHO having separate modules make easier to understand what is the purpose of those modules. For example, if we just need to use journal type, then we need to add a dependency to all dynamic-data-mapping-api, just for only one class.
> 
> Also, this module has the old implementation and the new one, which is confusing if you not are a member of DDM team, in my personal case it is really difficult to know which are the new implementation classes.
> 
> Please let me know what do you think about it.

Got it. I think we can go ahead with it :)
> 
> Regards,
> Eudaldo

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
resend here: https://github.com/liferay-echo/liferay-portal/pull/3414

**Pull request closed without merging**
