### PR TITLE
LPS-121801 Removing digital-signature

### PR DESCRIPTION
**Pull request by mateussgn**

### CODE REVIEW

**Comment by jeyvison** [comment]
hey @mateussgn , can you please fix the conflicts? Thanks

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:forward

**Comment by jpince** [comment]
@mateussgn @marcelabc thank you!

**Comment by mateussgn** [comment]
@jpince anytime! Let us know if you need anything more.

**Pull request closed without merging**
