### PR TITLE
LPS-125422 Make function to create repeated fields recursively so nested fields localized value is also cleared

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hey @oliveiraaraujo , can you please take a look at this one? thanks :)

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
