### PR TITLE
[TS] LPS-120004 Non localizable DDM fields are editable in all the languages

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-120004 Non localizable DDM fields are editable in all the languages, caused by  68b55c49e507ce8ea509c25d945113bb709092f4 , behaviour clarified in https://issues.liferay.com/browse/PTR-1943

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hey @marcelabc , can you please take a look at this one? Thanks :)

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
LGTM! @jeyvison

**Review by marcelabc — APPROVED** [review]
LGTM!

**Comment by jeyvison** [comment]
Thanks @marcelabc  :)

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
