### PR TITLE
LPS-125316 Verify if the value is not null

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
forwarded https://github.com/liferay-data-engine/liferay-portal/pull/129

**Comment by marcosapmf** [comment]
ci:close

**Pull request closed without merging**
