### PR TITLE
LPS-129325 SF - upgrading the nested fields before concatenating reduces the amount of iterations and doesn't change results

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related issues: https://issues.liferay.com/browse/LPS-129325, https://issues.liferay.com/browse/LPS-129384

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Hi, @achaparro.

Could you please take a look at this cc5e66e and verify whether we can make this arrangement? As I understand, this wasn't already released to our community, right?

Thanks in advance.

**Comment by rodrigopaulino** [comment]
LGTM. But, please, wait for [the answer](https://github.com/liferay-data-engine/liferay-portal/pull/347#issuecomment-803085000) before forwarding.

Thanks.

**Comment by rodrigopaulino** [comment]
ci:forward

**Comment by achaparro** [comment]
Hi @rodrigopaulino,

This change is fine since you can do this kind of switch in master before being published in ee branches.

However, I have checked the current upgrade process in 7.3.x and we have a critical issue caused by https://issues.liferay.com/browse/LPS-125267

We added this:
```
		registry.register(
			"3.9.1", "3.10.0",
			new com.liferay.dynamic.data.mapping.internal.upgrade.v3_10_0.
				UpgradeDDMFormInstanceRecord());
```
And there is no path in master for 3.10.0 so customers in 7.3 won't be able to upgrade to newer versions.

I know that you are working on it here:
https://github.com/liferay-data-engine/liferay-portal/pull/344
(I will review it and comment there if necessary)

But, can you guys @carolmariaabb, @rodrigopaulino, @natocesarrego and the rest of the team check this case to avoid these issues in the future? Upgrade processes and schema versions need to be synced among all branches so there is always a valid upgrade path for all cases.

Thanks.

**Comment by rodrigopaulino** [comment]
Thanks a lot for always helping, @achaparro!

As you could see, I already sent a PR to fix that. It's just waiting for the team's review.
Probably today, it will be forwarded.

Kind regards.

**Pull request closed without merging**
