### PR TITLE
LPS-133614 Remove condition for Fieldset when he is render

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-133614

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1257401_1043

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Hello, @rodrigopaulino . Thanks for notify me, I searched deeper into the code and found the source of the problem. I realized that in fact, this solution would be like masking the real bug, a mistake of mine. I'm gonna work in this new solution.

The problem happens because the function `getDDMFormFieldSettingsContext` inside of `dataConverter.es.js` convert every settings witch has a map of values include `placeholder` and `tip`, into a simple string except the `label`

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@danvb112 the unique failure seems to be related to your changes. Could you please verify that? Let me know if you need any assistance with that.
Thx

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1087401_7531

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by guilhermedcamacho** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
Resent in #527

**Pull request closed without merging**
