### PR TITLE
LPS-125969 Enable autofocus for forms

### PR DESCRIPTION
**Pull request by victorg1991**
This is a follow-up pr of https://github.com/liferay-data-engine/liferay-portal/pull/138

### CODE REVIEW

**Comment by jeyvison** [comment]
cc: @natocesarrego

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
Hi @victorg1991  :) I was just testing here and although there is no focus for the Data Engine structure when change the language we are scrolled up because the focus go to the title of the article. It seems like it's not the desirable behavior right?

**Comment by victorg1991** [comment]
Hi @jeyvison I'll take a look, I swear I tried it last week and it was working fine. At first glance it seems related to the multiple renders of the react app, I'll let you know if I find something

**Pull request closed without merging**
