### PR TITLE
LPS-131636 Retrieve the fields validation and pass it to the frontend

### PR DESCRIPTION
**Pull request by EliveltonR18**
Hi reviewer, 

This alterations are responsible for retrieve the validations of fields from backend, the changes are related wih this [issue](https://issues.liferay.com/browse/LPS-131636).

### CODE REVIEW

**Comment by EliveltonR18** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
