### PR TITLE
LPS-124596 store other available languages values into dataRecordValues just like we do for non-repeatable fields

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-124596

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by oliveiraaraujo** [comment]
LTGM!

**Review by jeyvison — APPROVED** [review]
LGTM!

**Comment by jeyvison** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
