### PR TITLE
LPS-130271 bug DM multiple upload with DE

### PR DESCRIPTION
**Pull request by boton**
Hi guys,

I apply the @rodrigopaulino suggestions in the previous PR liferay-data-engine#416.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
resend: https://github.com/liferay-data-engine/liferay-portal/pull/442. 

> Hi guys,

I apply the @rodrigopaulino suggestions in the previous PR #416.

**Pull request closed without merging**
