### PR TITLE
[DE-Migration] LPS-125543 Some fields have maps as values

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-125543

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Review by jeyvison — CHANGES_REQUESTED** [review]
Hi @rodrigopaulino!

Can you please sort these? : 

https://github.com/liferay-data-engine/liferay-portal/pull/118/commits/cb3b5343502fbe6be4952d0ffe7b32defba10b8c#diff-b41d54bd1fe8c9e86e51af8165fcce698d63c3b3d7b40b7f267a9bc866e2aa99R172-R178

https://github.com/liferay-data-engine/liferay-portal/pull/118/commits/cb3b5343502fbe6be4952d0ffe7b32defba10b8c#diff-4b2de1d0236005170fc53069bb5bf9650f04d657b44acd73ca4d7033feb508fcR52-R54

https://github.com/liferay-data-engine/liferay-portal/pull/118/commits/cb3b5343502fbe6be4952d0ffe7b32defba10b8c#diff-21e838073ea4f97d5e50aba388a68f45014bef5338f48736aca387111d565254R73-R77

Also i think the **if** you introduced falls in the same case that i mentioned [here](https://github.com/liferay-data-engine/liferay-portal/pull/110#issuecomment-756278587)  to @victorg1991 .

Looks like you're trying to fix similar problems?

**Comment by rodrigopaulino** [comment]
> Hi @rodrigopaulino!
> 
> Can you please sort these? :
> 
> [cb3b534#diff-b41d54bd1fe8c9e86e51af8165fcce698d63c3b3d7b40b7f267a9bc866e2aa99R172-R178](https://github.com/liferay-data-engine/liferay-portal/commit/cb3b5343502fbe6be4952d0ffe7b32defba10b8c#diff-b41d54bd1fe8c9e86e51af8165fcce698d63c3b3d7b40b7f267a9bc866e2aa99R172-R178)
> 
> [cb3b534#diff-4b2de1d0236005170fc53069bb5bf9650f04d657b44acd73ca4d7033feb508fcR52-R54](https://github.com/liferay-data-engine/liferay-portal/commit/cb3b5343502fbe6be4952d0ffe7b32defba10b8c#diff-4b2de1d0236005170fc53069bb5bf9650f04d657b44acd73ca4d7033feb508fcR52-R54)
> 
> [cb3b534#diff-21e838073ea4f97d5e50aba388a68f45014bef5338f48736aca387111d565254R73-R77](https://github.com/liferay-data-engine/liferay-portal/commit/cb3b5343502fbe6be4952d0ffe7b32defba10b8c#diff-21e838073ea4f97d5e50aba388a68f45014bef5338f48736aca387111d565254R73-R77)
> 
> Also i think the **if** you introduced falls in the same case that i mentioned [here](https://github.com/liferay-data-engine/liferay-portal/pull/110#issuecomment-756278587) to @victorg1991 .
> 
> Looks like you're trying to fix similar problems?

Hey, @jeyvison. I can't sort those. It was the sourceFormatter who did it.
In regards to your comment to Victor's PR, we can't treat the Map objects in the else clause because their string values are not proper serialized JSON. It will cause problems with parsing. Also, what Victor is doing is basically the same thing as I am with a different approach, but I'm not sure which one of those will perform better. ;)

**Comment by jeyvison** [comment]
> Hey, @jeyvison. I can't sort those. It was the sourceFormatter who did it.

Got it.

> In regards to your comment to Victor's PR, we can't treat the Map objects in the else clause because their string values are not proper serialized JSON. It will cause problems with parsing. Also, what Victor is doing is basically the same thing as I am with a different approach, but I'm not sure which one of those will perform better. ;)

Humm. understood. But we don't need the **else** anymore right? Or we dont need this if. Since we are considering that everything that falls under **else** is a Map we can just move this logic to there. Am i right?

**Comment by jeyvison** [comment]
@rodrigopaulino You're completely right!

@victorg1991 Can you check if this PR fix your LPS? If it does i think i'll foward this one. 

Thanks a lot to you both!

**Comment by victorg1991** [comment]
Sure @jeyvison You can send this one, it is almost the same code as mine. In my pr another bug was also solved so I'd create another lps for that and sent it separately

Thanks!

**Comment by victorg1991** [comment]
I've sent the pr again here: https://github.com/liferay-data-engine/liferay-portal/pull/121 and add a commit as the other commit depended on this

**Comment by jeyvison** [comment]
Awesome! Thanks a lot @victorg1991 !

**Comment by jeyvison** [comment]
ci:forward

**Review by jeyvison — APPROVED** [review]
LGTM!

**Comment by jeyvison** [comment]
Hi @rodrigopaulino , i'm  forwarding victor's PR instead because he's is fixing his case on top of your PR and the tests are already ok there

**Pull request closed without merging**
