### PR TITLE
LPS-125128 baseline

### PR DESCRIPTION
**Pull request by marcosapmf**
Follow up with changes requested in https://github.com/brianchandotcom/liferay-portal/pull/97395#issuecomment-754814676

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
resent to https://github.com/liferay-data-engine/liferay-portal/pull/108

**Pull request closed without merging**
