### PR TITLE
LPS-127725 Verify if the request contains the parameter

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Review by rodrigopaulino — COMMENTED** [review]
Discard comment.

**Comment by rodrigopaulino** [comment]
I'll be sending a new one.

**Comment by victorg1991** [comment]
Hey @rodrigopaulino, I've seen your comment over email, just in case you try that out, that line you mentioned was changed a couple of days ago: https://github.com/brianchandotcom/liferay-portal/pull/98674

**Pull request closed without merging**
