### PR TITLE
[TS] LPS-123415 - Non localizable DDM boolean fields are editable in all the languages when child of a separator field and contains the name of the separator

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
[TS] LPS-123415 - Non localizable DDM boolean fields are editable in all the languages when child of a separator field and contains the name of the separator
https://issues.liferay.com/browse/LPS-122104

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by jeyvison — APPROVED** [review]
LGTM!

**Comment by jeyvison** [comment]
ci:forward

**Pull request closed without merging**
