### PR TITLE
LPS-125203 Adds defaultLanguageId to props

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
resent to https://github.com/liferay-data-engine/liferay-portal/pull/81

**Pull request closed without merging**
