### PR TITLE
LPS-129826 prevent dropping a field into a fieldset

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-129826

**Note:** This a follow up for LPS-129826 that fix the case where the user tries to drop a field into a fieldset. Despite of the original issue being fixed in #364, we detected this other one that is very close to that, so we decided to use the same ticket to fix it since drag and drop complement each other.

### CODE REVIEW

**Comment by marcosapmf** [comment]
This a follow up for [LPS-129826](https://issues.liferay.com/browse/LPS-129826) that fix the case where the user tries to drop a field into a fieldset. Despite of the original issue being fixed in https://github.com/liferay-data-engine/liferay-portal/pull/364, we detected this other one that is very close to that, so we decided to use the same ticket to fix it since drag and drop complement each other.

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@marcosapmf the failure reported by CI is common to all our pull requests. Apparently, some change was introduced to portal-impl without changing its version.

**Comment by rodrigopaulino** [comment]
Resent https://github.com/liferay-data-engine/liferay-portal/pull/377

**Pull request closed without merging**
