### PR TITLE
LPS-127462 Allow deletion of referenced data definitions for all App Builder's content types

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related issue: https://issues.liferay.com/browse/LPS-127462

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
Failure related to the fix: missing the placement of `allowReferencedDataDefinitionDeletion` in `FieldSetModal.es.js` as well.

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Just started reviewing :)

**Comment by marcosapmf** [comment]
The failures seem to be flaky since they have passed when running locally.

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:forward

**Pull request closed without merging**
