### PR TITLE
LPS-129325 we need to add the field value into its parent field value if it is not there yet

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issues: https://issues.liferay.com/browse/LPS-129325, https://issues.liferay.com/browse/LPS-129384

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Just started reviewing.

**Comment by rodrigopaulino** [comment]
We're going to handle this over upgrade process in order to avoid technical debt.

**Pull request closed without merging**
